### ISSUE TITLE
Completely unusable in latest version of release...

### ISSUE THREAD

**Issue by HexBugOrion** [misode/misode.github.io#102]
I have tried using this generator for a custom dimension and it will not work AT ALL, I tred finding other but this is the only one I could ever find-
I don't know if it's still being worked on and if it isn't, well I guess I'll never use it.

**Comment by HexBugOrion** [comment]
Ignore this, I found out a workaround-

**Comment by misode** [comment]
If you're making custom dimensions in the latest snapshots, you may want to try the [new generator](https://misode.github.io/dev/worldgen/). It supports the different worldgen files for datapacks.
