### ISSUE TITLE
20w30a and changes for worldgen

### ISSUE THREAD

**Issue by Amirhan-Taipovjan-Greatest-I** [misode/misode.github.io#106]
A new snapshot (20w30a) has been released! In this snapshot: 
Added:  `Foliage_color`, `grass_color_modifier`,` temperature_modifier`, `creature_spawn_probability` and `Grass_color` parameters.
Changed: `sky_color` parameter now in the `Effects` category.
Also changed `Configured_feature` files.

I think what these changes (and other changed that I could forget) must be added to the Generator for actualization.

**Comment by misode** [comment]
These changes have been implemented in [minecraft-schemas](https://github.com/misode/minecraft-schemas). You can go to https://misode.github.io/dev/worldgen/biome/ to try them.
