### ISSUE TITLE
World Settings Generator changing defauls of nether and end.

### ISSUE THREAD

**Issue by RedBed24** [misode/misode.github.io#108]
When trying to change the generator settings or the dimensions type of the nether and end dimensions it changes all parameters to the overworld default making it difficult to change only one thing, or maintaing the nether and end presets.

**Comment by SPGoding** [comment]
Please use the improved version instead: https://misode.github.io/dev/dimension.

You can input `minecraft:nether` and then switch to Custom. All default settings from the nether preset are preserved.
