### ISSUE TITLE
Import tables?

### ISSUE THREAD

**Issue by CodeNinja212** [misode/misode.github.io#113]
Maybe adding a feature that can parse and import pre-existing loot tables onto the generator?
I've been using the generator, but it's difficult if I want to use a vanilla loot table and add a separate pool without either doing everything manually or editing the file itself, possibly making the table malformed.

This may be a bit tricky but can prove a good feature.

**Comment by misode** [comment]
You can paste your loot table in on the right side of the page. If you have any idea on how to make this more obvious feel free to tell me!

**Comment by CodeNinja212** [comment]
> You can paste your loot table in on the right side of the page. I'm open for ideas on how to make this more obvious!

It feels so subtle, but thanks. If you ask me, I think it may be better if you add a note under the loot table box(where it is generated and imported) on how to import tables, or an extra button within "More" under "Hide Source" named "Import" that will show a small pop-up on how to import pre-existing tables.
