### ISSUE TITLE
Complications with folder layout

### ISSUE THREAD

**Issue by C-InfDef** [misode/misode.github.io#116]
I was having trouble with creating a datapack and couldn't find a recent template, so I decided to research and create a little guide for what files and folders are in datapacks.

** This is the text document containing all the folders and files needed:**
[Datapack Folder Layout WIP.txt](https://github.com/misode/misode.github.io/files/5212890/Datapack.Folder.Layout.WIP.txt)
**This is the alternate version of the text document in PNG form as well as containing color coded files and symbols.**
![Datapack Layout WIP](https://user-images.githubusercontent.com/71182637/93000518-3a8a0280-f4e6-11ea-9643-f1cacfdb1b34.png)
** I also have created a ZIP containing the layout for easier datapack Creation.**
[1.16.3 Datapack Template.zip](https://github.com/misode/misode.github.io/files/5213024/1.16.3.Datapack.Template.zip)

**Comment by misode** [comment]
What is the issue exactly? I'm happy to provide some sort of explanation but remember that this is a tool and not documentation or a guide.
