### ISSUE TITLE
Allow customization of noise field names

### ISSUE THREAD

**Issue by Prospector** [misode/misode.github.io#126]
Somewhere have a field for setting a custom name for altitude, temperature, humidity, and weirdness in the UI. Since these names are arbitrary and can be used for any parameter, being able to rename them would help me be able to keep the values straight in my head and not constantly forget which one is for which.

**Comment by misode** [comment]
I'm working on this while trying to make it as general as possible. Would this fit your needs?
This will allow you to rename or hide any feature from a context path.

![image](https://user-images.githubusercontent.com/17352009/102435481-f93e4d00-4016-11eb-809a-a760c431cd31.png)

**Comment by misode** [comment]
:tada: This functionality has now been added! It allows you to rename or hide any field using its context path (these are the same that are used for translation keys). You can navigate to "Field Settings" by clicking the gear at the top.

![image](https://user-images.githubusercontent.com/17352009/102543935-576d3d80-40b4-11eb-9d3c-f74854756dcd.png)
![image](https://user-images.githubusercontent.com/17352009/102543923-53412000-40b4-11eb-9772-12ddfc762f61.png)

**Comment by SPGoding** [comment]
Would it be a good idea to add a button (or right click option?) to copy the context path of a field?

**Comment by misode** [comment]
This feature is now fully implemented. Thank you for the idea!
