### ISSUE TITLE
Large lag spikes when changing options.

### ISSUE THREAD

**Issue by LaserSlime** [misode/misode.github.io#130]
My loot table has around 600 lines with all the formatting and everytime I change something, the entire tab freezes for about 7 seconds. This wasn't the case in earlier versions of the ui.

**Comment by misode** [comment]
I've noticed this as well. Definitely a big issue.

**Comment by LaserSlimeHD** [comment]
Maybe add an option to disable automatic loot table generation. So you can change a lot of stuff at once and then press a "generate" button to generate the loot table and test it out. (If the generation is causing lag)

**Comment by misode** [comment]
> Maybe add an option to disable automatic loot table generation. So you can change a lot of stuff at once and then press a "generate" button to generate the loot table and test it out. (If the generation is causing lag)

The bottleneck is that every time you change a value, it re-renders the entire visual tree diagram from scratch. Generating the JSON is as simple as turning the in-memory JavaScript object into JSON.

**Comment by misode** [comment]
@LaserSlimeHD After profiling I found an 8x performance improvement. I've implemented this in fc748fefb8a5c1a93b652bcd6b2d706f3470a8d1. I will keep this issue open for future optimizations.

![image](https://user-images.githubusercontent.com/17352009/107098318-351fb280-680f-11eb-9adf-589107108ffd.png)

**Comment by LaserSlimeHD** [comment]
Just wanted to thank you for fixing this so quickly. This is literally the only good and up to date loot table generator I could find. All the other ones are outdated and missing lots of important features.

**Comment by misode** [comment]
Still not done with this, but 241d5229323d7a1729529919b1bc82f812ae96f8 reduced lag spikes quite a lot. Closing for now.
