### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by rtbittaker** [misode/misode.github.io#131]
It would be amazing if the generator also did Floating Islands World Gen.

**Comment by misode** [comment]
Hi! This is already possible. You just need to set the generator settings to `floating_islands`
[https://misode.github.io/dimension/?q=...](https://misode.github.io/dimension/?q=eyJ0eXBlIjoibWluZWNyYWZ0Om92ZXJ3b3JsZCIsImdlbmVyYXRvciI6eyJ0eXBlIjoibWluZWNyYWZ0Om5vaXNlIiwic2VlZCI6LTE1MDU3NzAyNDksImJpb21lX3NvdXJjZSI6eyJ0eXBlIjoibWluZWNyYWZ0OnZhbmlsbGFfbGF5ZXJlZCIsInNlZWQiOi0xNTA1NzcwMjQ5fSwic2V0dGluZ3MiOiJtaW5lY3JhZnQ6ZmxvYXRpbmdfaXNsYW5kcyJ9fQ==)
