### ISSUE TITLE
Downloading Extra JSON

### ISSUE THREAD

**Issue by TCM-Studios** [misode/misode.github.io#133]
There's this bug I've been noticing when using the Feature Generator that when I make a feature, the download sometimes has extra text that doesn't appear in the preview to the right. I attached an example, because I'm lousy at explaining. The extra.json is the wrong one and the right.json is what it should be. All I did for this example is loaded up the ore_granite preset and then removed the count parameter. I'm no expert, but I think what's happening is it's downloading the JSON with previous parameters that are saved in the background. It downloads correctly if I copy what shows, load a preset, then paste it back in.
[examples.zip](https://github.com/misode/misode.github.io/files/6112082/examples.zip)

**Comment by misode** [comment]
@TCM-Studios Your zip file only includes the `right.json` file so it's hard to see what the issue is. Could you include full reproduction steps, screenshots, and/or corresponding files?

**Comment by TCM-Studios** [comment]
Oh, sorry about that. I could have sworn that I had attached more files. I'll make a new example because I can't seem to find the second file.

**Comment by TCM-Studios** [comment]
Steps
1 Go to misode.github.io
2 Press Worldgen
3 Press Feature
4 Load "ore_granite" preset (It works with all of the other things I've tried as well. Granite is just a random example)
5 I replace the "minecraft:decorated" feature right after the "minecraft:square" decorator with custom "minecraft:ore"
6 I fill out the ore feature options.
7 The preview to the right (which is the correct code) shows :
`{
  "type": "minecraft:decorated",
  "config": {
    "decorator": {
      "type": "minecraft:count",
      "config": {
        "count": 2
      }
    },
    "feature": {
      "type": "minecraft:ore",
      "config": {
        "size": 64,
        "discard_chance_on_air_exposure": 0,
        "targets": [
          {
            "target": {
              "predicate_type": "minecraft:tag_match",
              "tag": "minecraft:base_stone_overworld"
            },
            "state": {
              "Name": "minecraft:gold_block"
            }
          }
        ]
      }
    }
  }
}`
8 I download it
9 The download is "example.json" in the new zip folder.
Again sorry for only sending one of the files in the original comment.
[example.zip](https://github.com/misode/misode.github.io/files/6120664/example.zip)

**Comment by misode** [comment]
Thanks for your report! It was a silly one line mistake 😝

**Comment by TCM-Studios** [comment]
Hey, no problem! I know what it's like to have a tiny error like that! Have a good day.
