### ISSUE TITLE
Generator doesn't load on Firefox for version 1.17

### ISSUE THREAD

**Issue by xhendrikg** [misode/misode.github.io#136]
I tried it on iphone and windows 10 and it doesnt load

**Comment by misode** [comment]
Could you provide some more information, like screenshots and browser version?

**Comment by xhendrikg** [comment]
![grafik](https://user-images.githubusercontent.com/69456711/114007457-a9072700-9861-11eb-8640-0e4b47b215bc.png)
![grafik](https://user-images.githubusercontent.com/69456711/114007518-b58b7f80-9861-11eb-90d1-cfbc77786bec.png)
I cleared my full cache and the 1.17 Version doesnt load in firefox on any device from me. I tried loading the 1.17 one on my laptop and it does work there too.
![grafik](https://user-images.githubusercontent.com/69456711/114007709-da7ff280-9861-11eb-9dc2-2bb99acfbede.png)1.16 works

**Comment by misode** [comment]
I've heard of someone else having this problem and I don't immediately know why it happens. I also can't reproduce myself on Firefox so it depends on some security settings. I recommend using a different browser.

**Comment by xhendrikg** [comment]
> I've heard of someone else having this problem and I don't immediately know why it happens. I also can't reproduce myself on Firefox so it depends on some security settings. I recommend using a different browser.

The 1.16 one works, can you maybe try changing the 1.17 one more to the 1.16 one

**Comment by misode** [comment]
When the version is set to 1.17, the generator needs to do extra work to make sure the data is up-to-date. This includes fetching data from github repositories. This can't easily be fixed unfortunately.

**Comment by Gamemap** [comment]
@xhendrikg 
I have found a way to run version 1.17.

1. Select 1.16
2. Select 1.17
3. select a preset

After that the 1.17 version works until the page is reloaded.

I don't know why this worked. (I just tried a lot).
I hope it helps you to use the 1.17 version.

**Comment by misode** [comment]
@xhendrikg @Gamemap I pushed some changes which fixed this. Can you both confirm this is no longer an issue?

**Comment by Gamemap** [comment]
Yes, it is working.

Thank you for this generator.

**Comment by xhendrikg** [comment]
It works on my laptop, i need to try on my computer.

**Comment by misode** [comment]
Fixed. This was caused by the Cache API failing. When it detects it can't access the cache it does a normal fetch.

**Comment by xhendrikg** [comment]
> 
> 
> It works on my laptop, i need to try on my computer.

Works on computer :)
