### ISSUE TITLE
Missing Some Worldgen Setting

### ISSUE THREAD

**Issue by JeffSyu** [misode/misode.github.io#138]
I found some tags been missed or had been changed when inspecting the latest vanilla worldgen file(21w15a)
Noise setting : `min_surface_level` filed is missed
Features : 
`wetness_mean` and `wetness_deviation` had been removed from `minecraft:dripstone_cluster` feature due to `wetness` float provider

**Comment by misode** [comment]
Thanks! These and a bunch of other issues were fixed in dbe0f4bd822974ca81247e40623a929af249f202.
