### ISSUE TITLE
[Suggestion] Commands

### ISSUE THREAD

**Issue by DillonB07** [misode/misode.github.io#140]
With datapacks you can create `/trigger` commands.
Would it be possible to add this so that you can put some text that you want to display to the player who runs that command?
This could be a `/tellraw` that uses the `@p` identifier.

**Comment by misode** [comment]
Are you asking for a [text component](https://minecraft.gamepedia.com/Raw_JSON_text_format) generator? There's currently no plans for this, a fairly common alternative is https://www.minecraftjson.com/.

**Comment by DillonB07** [comment]
No. I was asking for a feature that allows you to create `/trigger` commands. Also, a far better tellraw generator is: https://minecraft.tools/en/tellraw.php or for just JSON: https://minecraft.tools/en/json_text.php

**Comment by misode** [comment]
The generators on my site are only for a single data pack json file, not for parts of a data pack. I see how it would be useful to you, but it's out of scope for this project.
