### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by xhendrikg** [misode/misode.github.io#145]
Do you use a translation Tool That other people can help to translate the website in other languages? I selected German and nothing changed

**Comment by misode** [comment]
Hi! You can find the translation project here: https://l10n.spgoding.com/projects/minecraft-schemas/minecraft-schemas/
Changing the language to German worked for me. If it's still not working, could you give some more information, like what page you are on, a screenshot, etc?

**Comment by Gamemap** [comment]
I use the newest Firefox version and Windows 10 and German works fine for me.

**Comment by xhendrikg** [comment]
> Hi! You can find the translation project here: https://l10n.spgoding.com/projects/minecraft-schemas/minecraft-schemas/
> 
> Changing the language to German worked for me. If it's still not working, could you give some more information, like what page you are on, a screenshot, etc?
> 
> 
> 
> Edit: I realize this is probably related to the Firefox issue #136 

Whould be nice if you link the Link in the GitHub respo readme. And the translation issue isn't a issue anymore. I thought it wasn't working because the first page where you can change the language it wasn't translating but when you like click on world generation it translates. Is it possible to translate the things that are on the page where you select world gen, predicate and more? Whould be nice

**Comment by misode** [comment]
Added the info to the README
