### ISSUE TITLE
Suggestion: Worldgen datapack merger

### ISSUE THREAD

**Issue by FokaStudio** [misode/misode.github.io#150]
Idk if I am allowed to post suggestions here, but I will give it a shot
It is painful to edit all .json files of worldgen datapack to make 2 work with each other (because almost everyone knows that 2 worldgen datapacks that modify the same biomes are automatically incompatible, and only 1 will work)
This is also hard if you have a giant datapack, like e.g. Wiliam Wyther's Overhauled Overworld and you are trying to make it work with 1.18 previews. (this is just an example!)

A tool like this would be just amazing and would speed up that process by a lot!

**Comment by misode** [comment]
Awesome idea, but out of scope for this repository
