### ISSUE TITLE
[Question] - River biom on floating islands

### ISSUE THREAD

**Issue by Gamemap** [misode/misode.github.io#152]
Is it possible that I can create a river biome with water in it on floating islands without a sea level above 0, so that the floating islands are not in water?
Would I have to create a custom biome for that? Is it possible to configure a riverbed and biom generated water with custom biomes?
![floating islands + river](https://user-images.githubusercontent.com/71942164/121776197-ca4f0100-cb8b-11eb-81d0-d26ea3db0460.png)

**Comment by misode** [comment]
This is not a place to get help making custom worlds. I recommend asking your question on the [Minecraft Commands Discord](https://discord.gg/QAFXFtZ).

**Comment by Gamemap** [comment]
I can understand you. Sadly I can't have Discord, but I will search for a other Plattform.

Thank you,
Gamemap

**Comment by misode** [comment]
There is a [Subreddit](https://www.reddit.com/r/MinecraftCommands/) and a [StackExchange](https://gaming.stackexchange.com/?tags=minecraft-commands) for Minecraft commands.

**Comment by Gamemap** [comment]
Thank you very much!
