### ISSUE TITLE
Error when loading share link

### ISSUE THREAD

**Issue by At-Developper** [misode/misode.github.io#156]
When I try to use the item modifier generator this page pops up, this is also the case on my pc.
![6D2CD9F6-A419-44E7-A597-D4624294FDA4](https://user-images.githubusercontent.com/61563122/125093269-6d832f80-e0d2-11eb-988f-53f20ba63701.jpeg)

**Comment by misode** [comment]
I got rid of link sharing. But maybe loading should still work for existing links.
