### ISSUE TITLE
Empty field gets force replaced

### ISSUE THREAD

**Issue by InQuognito** [misode/misode.github.io#157]
An empty 'extra' field inside a set_lore function keeps getting force-replaced whenever I delete it and then edit any other different field.
![image](https://user-images.githubusercontent.com/44120299/125198928-94a04500-e229-11eb-9b41-e638129ee665.png)

Steps to Reproduce:
1) Make an item in a loot table.
2) Add the set_lore function.
3) Add a piece of lore.
4) Add an extra field and fill it in with whatever.
5) Delete the actual lore INSIDE the extra field (NOT the extra field)
6) Delete the extra field.
6) Type something into a different field to refresh the generator, and the empty/null extra field should reappear. But knowing programming, it probably won't, because rule of bugs says if you try to show it to someone else, it won't happen.

**Comment by misode** [comment]
Thanks for the report with clear steps to reproduce, it helped a ton! The issue should now be fixed.
