### ISSUE TITLE
Pressing enter in a textbox field unfocuses it

### ISSUE THREAD

**Issue by jackomix** [misode/misode.github.io#160]
Using the visualizer for noise settings is very useful. If I type in a value and press enter, the visualizer updates and I can see what happened. But then if I try to backspace, it exits the page, and I have to go back and refill some values. This is because when you press enter, the text box is unfocused, so having it stay focused would solve this issue.

Besides that, awesome tool!

**Comment by misode** [comment]
Losing focus when pressing enter is standard browser behavior. It's what people expect to happen when you press enter.

Ideally the visualizer would update immediately without needing you to press enter, but for performance reasons this is currently not doable.

**Comment by jackomix** [comment]
Perhaps have the visualizer wait for no keyboard input for 0.5 or 1 second before updating?

**Comment by misode** [comment]
@jackomix #155 seems to have fixed this. My bad I was actually wrong when I said losing focus was standard behavior, this was a consequence of redrawing the whole tree on every update.
