### ISSUE TITLE
Noise is not displayed in full Chrome window

### ISSUE THREAD

**Issue by maityyy** [misode/misode.github.io#163]
Noise is not displayed when Chrome window is open at full size (first screenshot). However, this is resolved when the browser window takes up half of the screen (second screenshot).
![image](https://user-images.githubusercontent.com/47220489/130680912-19059591-078a-4869-b4b0-9e97cf7f606f.png)
![image](https://user-images.githubusercontent.com/47220489/130680968-7d8e629a-9d4a-4702-86ae-903aef54b47b.png)

**Comment by misode** [comment]
It is behind the JSON output, which you can collapse
