### ISSUE TITLE
error on page Dimension Generator

### ISSUE THREAD

**Issue by slit-bodmod** [misode/misode.github.io#164]
Something went wrong rendering the generator: e.addEventListener is not a function
If you think this is a bug, you can report it on GitHub

**Comment by misode** [comment]
Do you have steps to reproduce? The JSON contents or any actions that you took would be really helpful!

**Comment by slit-bodmod** [comment]
Hmm, well it came up when I first opened the page idk, it could just be my
browser being weird

**Comment by misode** [comment]
Most likely fixed by 9671f304f77a9638609f6ba073b6f9cf26987066. Please comment if this happens again in the future.
