### ISSUE TITLE
Add Spanish translation

### ISSUE THREAD

**Issue by kevinrpb** [misode/misode.github.io#165]
Hi! I would like to contribute to the project translations (https://l10n.spgoding.com/projects/minecraft-schemas/minecraft-schemas/).

I'm a native Spanish speaker (from Spain). Do you think you could add the language to the project so I can give a hand with it? 😄

**Comment by misode** [comment]
I've added Spanish as translation option to the project. Thanks for willing to contribute!

**Comment by kevinrpb** [comment]
That's great! Thanks a lot for the work put into the project. It's great 😄
