### ISSUE TITLE
Suggestion: Generator For the New Datapack format 8 for new 1.18 snapshots. 

### ISSUE THREAD

**Issue by BluePhoenixLOL** [misode/misode.github.io#166]
So, Minecraft said in the patch notes for 21w37a, the first real 1.18 snapshot, they said they updated to data pack format 8. and i really want to make some datapacks for 1.18, like testing out the new way caves generate, adding new cave and mountain biomes and ect.

**Comment by misode** [comment]
The generators now support 1.18
