### ISSUE TITLE
[Suggestion] Add option to warn you when closing the tab

### ISSUE THREAD

**Issue by LaserSlime** [misode/misode.github.io#178]
It is really easy to accidentally close the tab before saving and loose all your changes. I've seen lots of websites use this feature where the browser displays a warning before closing the tab. Not sure how this works but it would be cool as an option so you can still turn it off if you don't want it.

**Comment by misode** [comment]
I personally find those warnings a bit annoying. Would you also be fine if it restores your last JSON when you open the page?

**Comment by LaserSlime** [comment]
> 
> 
> I personally find those warnings a bit annoying. Would you also be fine if it restores your last JSON when you open the page?

But that doesn't work with multiple tabs open. Like i said, there should be an option to turn the warning off.

**Comment by PugzAreCute** [comment]
Maybe use cookies/local storage to store the json which could be restored by say another drop-down like the "presets" drop-down?

**Comment by misode** [comment]
I implemented this by saving the file per generator type in local storage. When you exit and reload the page or switch generators, it gets the saved backup. When the backup exists, a button is shown in the project dropdown:
![image](https://user-images.githubusercontent.com/17352009/162335833-c4607e78-2547-4848-b89b-dcd01eff934d.png)

Let me know how this works for you and whether any changes should be made.
