### ISSUE TITLE
Revival of shared links

### ISSUE THREAD

**Issue by ChenCMD** [misode/misode.github.io#184]
If possible, I would like you to re-implement the shared link.
This is very useful for telling your friends about sound combinations, loot_table, advancement and more.

**Comment by misode** [comment]
Yes I would like this as well. Though I am not a fan of the long `?q=` parameter, I'd like to explore some other approaches, for example encoding just the edits that you've made

**Comment by misode** [comment]
I just added support for `preset=` and `version=`. My implementation is a bit hacky so if you can find any bugs let me know.
