### ISSUE TITLE
Pages are blank on mobile

### ISSUE THREAD

**Issue by ErrorCraft** [misode/misode.github.io#188]
When opening any page on mobile it displays a blank page.

![B3019B61-5109-45DA-97D3-C0E190450AE4](https://user-images.githubusercontent.com/51973682/144657261-afdbd004-8b1c-4d1a-b091-26898089c512.jpeg)
A very detailed image of a blank page.

**Comment by misode** [comment]
What is your device and browser version? Secondly, does the problem go away when reloading the page?

**Comment by ErrorCraft** [comment]
iOS 14 and Safari 14. It doesn't go away when reloading the page. It seems to load fine on iOS 15 and Safari 15 though.

**Comment by misode** [comment]
I have absolutely no clue what could be going on, and it's hard to figure out without seeing if there are any errors in the log.

**Comment by misode** [comment]
Unless someone has reproducible steps I'm going to close this for now
