### ISSUE TITLE
Error rendering the tree: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by Coosanta17** [misode/misode.github.io#189]
idk if this is a 1.17 - 1.18 thing, i think it is and i'm trying to upgrade my pack, is it possible for this to upgrade the format so it is compatible with 1.18 instead of showing an error? that would be greatly appreciated!

![image](https://user-images.githubusercontent.com/85379921/145345847-e7065895-a5f0-416c-9a59-9ac8196afff5.png)

**Comment by misode** [comment]
Hi, can you describe the steps to reproduce? I understand you had some JSON loaded and then changed the version from 1.17 to 1.18? What was that JSON?

For upgrading a datapack there is a separate page: https://misode.github.io/upgrader/

**Comment by Coosanta17** [comment]
I am so sorry I just realised feature format has changed for 1.18!
I am so silly!
