### ISSUE TITLE
Rendering Bug at certain Zoom Levels

### ISSUE THREAD

**Issue by PLB527097** [misode/misode.github.io#190]
![Zoom_Out](https://user-images.githubusercontent.com/92827422/146683306-7a92723f-ddf2-42fd-9b18-c75e428f6dfe.png)
![Zoom_In](https://user-images.githubusercontent.com/92827422/146683310-fba47cee-7ad0-4ff4-b60b-a6ea72286d4f.png)
I think it's fairly self explanatory that this is a bug. This is the dimension generator for 1.18, and the first image is taken at one zoom level, the second taken by zooming in once. This is on chrome.

It wouldn't be so much of an issue if there were a good way to alter the base octave of the noise generators, which I want to do anyway, but I'm not sure how that's even done on 1.18, or if it's even in the dimension file anymore.

**Comment by misode** [comment]
Hmm yes I also noticed this a few times when testing, but I had hoped no one would notice  👀
