### ISSUE TITLE
UI of advancement criteria is confusing

### ISSUE THREAD

**Issue by BaNaN4Ik-STOP** [misode/misode.github.io#191]
Hello, i'm BaNaN4Ik_STOP, and please fix criteria bug on your website. I creating own advancement pack, and when writing criteria not in a json file but on a website. Please fix this please fix this very bad bug. ~BaNaN4Ik_STOP~

**Comment by misode** [comment]
Hey, could you describe this bug a bit further? Do you have steps to reproduce, screenshots or a video?

**Comment by BaNaN4Ik-STOP** [comment]
Okey
![20211226_162803](https://user-images.githubusercontent.com/86436113/147409576-7d28845b-df1d-422a-a2ff-a68301c32a2e.jpg)

**Comment by misode** [comment]
You need to click the `+` button next to it, but I see how the UI is confusing

**Comment by BaNaN4Ik-STOP** [comment]
the fact of the matter is that when I press the + criterion remains the same as it was and from below near rewards there a new figurine appears
![20211226_163659](https://user-images.githubusercontent.com/86436113/147409832-1b9cf75c-1a83-4ff0-b3a6-622fbacf5977.jpg)

**Comment by Coosanta17** [comment]
that's what the "+" is meant to do... add another block/criteria

**Comment by misode** [comment]
I'm going to keep this open because I still have some plans to improve this
