### ISSUE TITLE
Bug: Technical Changelog not displaying

### ISSUE THREAD

**Issue by Jack-Papel** [misode/misode.github.io#200]
The technical changelog was not displaying for me
Chrome, Mobile. Android. Google Pixel.

![Screenshot_20220222-092917](https://user-images.githubusercontent.com/64770632/155186339-3f143ebe-ce01-4ada-b1db-daadd8cec4cf.png)

Refreshing did not solve the issue.
The search bar, the "sort by" button, and the "x" on the GitHub message were also nonfunctional.

The theme button and the language button were nonfunctional, but the GitHub button and the advertisement were working.

Clearing cookies for the site resolved the issue.

**Comment by misode** [comment]
This is a weird issue. The scripts somehow didn't load/run. But it seems like this hasn't been a reoccurring issue so I will close this for now.

**Comment by Jack-Papel** [comment]
Thanks
