### ISSUE TITLE
Can't get back into editing after error

### ISSUE THREAD

**Issue by Hwacivilongola** [misode/misode.github.io#201]
In a field where it asks for a block I had "minecraft:" and clicked off of the text field. When I did that it said 
> Something went wrong rendering the generator: Non [a-z0-9/._-] character in path of minecraft:
And now I can't get back into editing it besides removing the cookies.

**Comment by misode** [comment]
@Hwacivilongola On which page does this error show, and what text field specifically? Did you have the visualizer open?

**Comment by misode** [comment]
Okay I managed to reproduce with the following steps
1. Navigate to the [dimension generator](https://misode.github.io/dimension/)
2. Set the settings field to "inline"
3. Set the noise router barrier field to "reference" and input `minecraft:`

**Comment by misode** [comment]
This appears to be fixed now
