### ISSUE TITLE
Error: Biome Generator: "The minimum version for this generator is 1.16"

### ISSUE THREAD

**Issue by Eggosauria** [misode/misode.github.io#202]
The biome generator gives an error wich says that the minimum version is 1.16. I am using the 1.18.2 version. I think this is a bug as the biome generator is still functional. I included a screenshot of the error.

I also would like to know if it is possible to download the whole draft/project from the datapack generator. If so, how do I do it?

![github error](https://user-images.githubusercontent.com/91455592/156564699-442388fe-bc79-4b52-9a98-a166c3ffd5bc.png)

**Comment by misode** [comment]
I actually cannot reproduce this. Could you describe the exact steps to reproduce?

**Comment by Eggosauria** [comment]
I don't get the error anymore. I dont know what I did to get the error. If I get it again I will post it here. I was just working on a custom biome.
