### ISSUE TITLE
Rendering generator missing keys

### ISSUE THREAD

**Issue by SlimyRedstone** [misode/misode.github.io#207]
I was playing around custom dimension when this error popped up:

> Something went wrong rendering the generator: Missing key in minecraft:worldgen/density_function: minecraft:end/sloped_cheese

It does that with every "noise router" entry, and the added problem is that once this error is triggered, you can't get back to the page to modify that parameter. The only way I found to get back on that page is to do CTRL+F5 to force reload the cache.

**Comment by misode** [comment]
I'm having trouble reproducing this. Do you know the exact steps how to reproduce this?

**Comment by SlimyRedstone** [comment]
The steps I did where: 
1. Go to 'World Gen' then to 'Dimension'
2. Paste this JSON text into the text editor on the down right of the page 
`{"type":{"ultrawarm":false,"natural":true,"piglin_safe":false,"respawn_anchor_works":false,"bed_works":false,"has_raids":false,"has_skylight":true,"has_ceiling":false,"coordinate_scale":1,"ambient_light":1,"fixed_time":6000,"logical_height":320,"effects":"minecraft:overworld","infiniburn":"#minecraft:infiniburn_overworld","min_y":-64,"height":320},"generator":{"type":"minecraft:noise","seed":6.341646424596465e+21,"settings":{"sea_level":63,"disable_mob_generation":false,"aquifers_enabled":true,"ore_veins_enabled":true,"legacy_random_source":false,"default_block":{"Name":"minecraft:stone"},"default_fluid":{"Name":"minecraft:water","Properties":{"level":"0"}},"noise":{"min_y":-64,"height":320,"size_horizontal":1,"size_vertical":2,"sampling":{"xz_scale":1,"y_scale":1,"xz_factor":80,"y_factor":160},"bottom_slide":{"target":-0.234375,"size":0,"offset":0},"top_slide":{"target":-0.078125,"size":3,"offset":0},"terrain_shaper":{"offset":0,"factor":0,"jaggedness":0}},"noise_router":{},"surface_rule":{"type":"minecraft:sequence","sequence":[{"type":"minecraft:condition","if_true":{"type":"minecraft:vertical_gradient","random_name":"minecraft:bedrock_floor","true_at_and_below":{"above_bottom":5},"false_at_and_above":{"above_bottom":0}},"then_run":{"type":"minecraft:block","result_state":{"Name":"minecraft:bedrock"}}},{"type":"minecraft:condition","if_true":{"type":"minecraft:vertical_gradient","random_name":"minecraft:deepslate","true_at_and_below":{"absolute":0},"false_at_and_above":{"absolute":8}},"then_run":{"type":"minecraft:block","result_state":{"Name":"minecraft:deepslate","Properties":{"axis":"y"}}}}]}},"biome_source":{"type":"minecraft:multi_noise","preset":"minecraft:overworld"}}}
`
3. Then go under 'Generator' -> 'Generator Settings' -> 'Noise Router'
4. Then select, for exemple, in 'barrier' the option 'minecraft:overworld/base_3d_noise'

**Comment by misode** [comment]
Thank you very much, I'm able to reproduce. I will look into fixing this shortly!
