### ISSUE TITLE
Multi Noise Dimension map only show one biome

### ISSUE THREAD

**Issue by Raft08** [misode/misode.github.io#238]
Hello, 
I'm creating a dimension but the map only show one biome even if i zoom out

Here is my json: 
```{
  "type": "tgc:void_type",
  "generator": {
    "type": "minecraft:noise",
    "seed": 1735364268,
    "settings": "minecraft:floating_islands",
    "biome_source": {
      "type": "minecraft:multi_noise",
      "biomes": [
        {
          "biome": "minecraft:plains",
          "parameters": {
            "temperature": 0,
            "humidity": 0,
            "continentalness": 0,
            "erosion": 1,
            "weirdness": 0,
            "depth": 0,
            "offset": 0
          }
        },
        {
          "biome": "minecraft:forest",
          "parameters": {
            "temperature": 0,
            "humidity": 0,
            "continentalness": 0,
            "erosion": -1,
            "weirdness": 0,
            "depth": 0,
            "offset": 0
          }
        }
      ]
    }
  }
}
```

Here is an image

![image](https://user-images.githubusercontent.com/72615320/170830999-29c96d50-a834-4b51-963a-2ccc15f09d53.png)

And here is the link : https://misode.github.io/dimension/?share=26acda93-898d-4961-923c-51129b6e0040

Thanks, Raft

**Comment by Raft08** [comment]
I Finded out that Opera GX is the problem

**Comment by Raft08** [comment]
Sorry misclick

**Comment by misode** [comment]
The problem is caused by using the `floating_islands` settings. This causes the noise octaves to be initialized to all zeroes, which means the climate doesn't vary. The current way in which it gets the climate noise parameters is a bit hacky, it still doesn't work properly with density functions.

**Comment by Raft08** [comment]
Not actualy i tried on Edge and it work just wel! It's just OperaGX Browser
