### ISSUE TITLE
Github API is blocked in some countries

### ISSUE THREAD

**Issue by WarmthDiamond** [misode/misode.github.io#239]
I have a trouble on the loot table generator. 
When I try to choose an entry or a function, there's no item to choose.
I also tried to access the website on the Ubuntu and Win10 virtual machine, but the problem still existed.
Pictures are as follows.

![XMS2Hs](https://user-images.githubusercontent.com/106417939/170848357-08d9fb38-3b1e-4e11-b921-bf7c5c2a36ae.png)
![XMSgBj](https://user-images.githubusercontent.com/106417939/170848359-262b5f4f-e9b2-4a45-842e-aef7b2eec731.png)

**Comment by WarmthDiamond** [comment]
P.S.
I tested it on localhost and it still has this problem.

![QQ截图20220529123804](https://user-images.githubusercontent.com/106417939/170852527-608b3d29-36c4-431c-a88f-de56e08e4733.png)

**Comment by misode** [comment]
Could it be possible that `raw.githubusercontent.com` is blocked in your country?

**Comment by WarmthDiamond** [comment]
Thank you for the tip.
I found that there's DNS contamination existed in the network segment nearby.
This problem was resolved when I reconfigured the DNS server.

![uTools_1653828968976](https://user-images.githubusercontent.com/106417939/170870186-c7f091bf-7362-4d8a-a169-5ecc4847bd8b.png)

**Comment by misode** [comment]
An attempted fix was made in 0ecc69a86138e7ad50f65841de3306ddbf73e405. Can the people affected by this confirm that the site is now working? cc @ThatJadenXgamer

**Comment by ThatJadenXgamer** [comment]
apologies for the late replay, but It seems the issue has been fixed for me!

**Comment by misode** [comment]
Excellent to hear!
