### ISSUE TITLE
More Visual UI for Generators

### ISSUE THREAD

**Issue by DorkOrc** [misode/misode.github.io#241]
Would be incredibly useful to have a visual demonstration of what you're building, above where the JSON is, for example:
_Idea of what is might look like:_
![misode_generator_vision](https://user-images.githubusercontent.com/16517352/171228781-7e2491f6-f577-43a7-8678-5ce2df3a8df4.png)

- **Crafting Recipes**
  - All possible ways the crafting recipe allows the item to be crafted
  - For item tags/groups, it cycles through them
  - For item tags which are not recognised, perhaps it's just a question mark
- [Added] ~~Loot tables~~
  - ~~Brings up a single-chest UI with a random assortment of items from the loot table~~
  - ~~Has a lil 🎲 thing you can click to generate it again randomly~~
- **Advancements**
  - Shows what the icon looks like as well as what appears when you would hover over it
- **Chat types**
  - Shows what the chat might look like (for example, `sender` is a "Steve" and `contents` is "Hello, World")
 
Obvs doing graphics for the worldgen stuff is a whole other thing so I won't suggest that here lmao

**Comment by misode** [comment]
Thanks for all the suggestions! Some worldgen generators actually already have these visualizations. Click the blue play button

**Comment by misode** [comment]
Partly implemented in #293
