### ISSUE TITLE
Multiple Biome Option

### ISSUE THREAD

**Issue by PieCreeper12** [misode/misode.github.io#256]
I wanted to make a grass, snow, desert and stone dimension for a server but there seems to only be an option for 1 or all biomes. I don't want to spend hours deleting every biome that isn't a biome I want in the world. Maybe there can be an option to select which biomes you have in a world.

**Comment by misode** [comment]
With the `multi_noise` biome source you can create a dimension with just a few biomes. But this is not really the place to ask for help. You can either go to the Discussions tab or to the [MinecraftCommands discord](https://discord.gg/QAFXFtZ)
