### ISSUE TITLE
Chat Type generator presets do not work

### ISSUE THREAD

**Issue by DorkOrc** [misode/misode.github.io#260]
Choosing any [chat type preset](https://misode.github.io/chat-type/?version=1.19&preset=say_command) will just not work

![image](https://user-images.githubusercontent.com/16517352/178562080-7e89ddd7-1a75-4341-9f63-d0465c28c3cb.png)

**Comment by misode** [comment]
Oh right because the schemas are outdated since 1.19.1

**Comment by misode** [comment]
I decided to fix this by keeping the 1.19 schemas and just making sure that it fetches the 1.19 data, until 1.19.1 is released. The only [data changes](https://github.com/misode/mcmeta/compare/1.19-data-json..data-json) between the two are for chat type.

**Comment by misode** [comment]
I have updated the schemas and presets to 1.19.1 now
