### ISSUE TITLE
Trying to make data pack for deep dark and mangrove only but keep with  villner gen

### ISSUE THREAD

**Issue by WilliamMaber** [misode/misode.github.io#261]
trying to make a data pack that makes the overworld deep dark and mangrove bioms only any help?

https://misode.github.io/world/?share=5d5e26e7-e349-4fc8-8540-2143fa7e22b2

**Comment by misode** [comment]
This is not the best place to ask for help with data packs. Either use the discussions tab or ask on the [MinecraftCommands discord](https://discord.gg/QAFXFtZ).
