### ISSUE TITLE
Cannot load preset overworld in 1.16

### ISSUE THREAD

**Issue by Overcloud-SR-72** [misode/misode.github.io#265]
The noise preset of 1.16 overworld cannot be correctly loaded.
![Screenshot 2022-07-22 at 16-35-57 noise settings worldgen - Minecraft 1 18 1 18 2 1 19](https://user-images.githubusercontent.com/109810018/180462592-b9cd3edd-fcb7-4c0f-be89-a65f14f08b07.png)
The page:
https://misode.github.io/worldgen/noise-settings/?version=1.16
I simply press the “Presets” button, and then the “overworld” button in the list, and it shows the message:
“Cannot load preset overworld in 1.16
If you think this is a bug, you can report it on GitHub”

**Comment by misode** [comment]
I don't have enough information to reproduce the issue. Please mention the page you were on, and the exact steps that caused this error to appear.

**Comment by Overcloud-SR-72** [comment]
> 

The page:
https://misode.github.io/worldgen/noise-settings/?version=1.16
I simply press the “Presets” button, and then it shows the message:
“Cannot load preset overworld in 1.16
If you think this is a bug, you can report it on GitHub”

**Comment by misode** [comment]
@Overcloud-SR-72 Could you help me with these questions to troubleshoot the issue?

1. Is this the only preset that doesn't load or does it happen with all presets, across all versions?

2. Can you load https://raw.githubusercontent.com/misode/mcmeta/1.16.5-data-json/data/minecraft/dimension/overworld.json in your browser?

**Comment by Overcloud-SR-72** [comment]
Hello again,
1.No, all presets **WERE** not able to load, across all versions.
2.According to my **current** test, I **CAN** load it.
3.Also, **now** the website performs good on my computer.

I apologize for replying late because I was busy with other things for the recent month.
Thank you for solving the problem.
