### ISSUE TITLE
Persistent error message "This generator is not available in versions above 1.18.2"

### ISSUE THREAD

**Issue by Jack-McKalling** [misode/misode.github.io#272]
Once you select a generator that is unavailable, every generator you switch to then after, will have the same error message even if it didn't before.

How to produce:
- Go to main page https://misode.github.io/
- Click "all generators", and for instance "configured feature"
  (notice no error)
- Now click the down-arrow next to the page title and select "structure feature" to land on https://misode.github.io/worldgen/feature/
  (notice the error pops up)
- Now click the down-arrow again and select "configured feature" again
  (notice the error stays)

![misode generator bug](https://user-images.githubusercontent.com/14236702/181736679-96b2bf94-e24d-4b7a-8d36-3447efa5a656.png)

**Comment by misode** [comment]
This is not trivial to fix and will probably require a bit of a cleanup/refactor. When attempting to fix this I always ran into an infinite re-render loop

**Comment by misode** [comment]
This has now been fixed, along with that an improved error panel
![image](https://user-images.githubusercontent.com/17352009/221929423-7b40da38-5172-42a2-9dac-45464a58e7e7.png)
