### ISSUE TITLE
How can I set host to 0.0.0.0

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [misode/misode.github.io#278]
The default host is open at 127.0.0.1
But I need to modify his host
where should i modify

**Comment by misode** [comment]
See Vite's docs here: https://vitejs.dev/config/server-options.html#server-host

**Comment by Thexiaoyuqaq** [comment]
小雨已收到你的来信已存放至小雨的收件箱

**Comment by Thexiaoyuqaq** [comment]
thank
