### ISSUE TITLE
Error when importing a non-syntactically correct crafting recipe

### ISSUE THREAD

**Issue by DorkOrc** [misode/misode.github.io#281]
```json
{
    "type": "minecraft:smelting",
    "ingredient": {
        "item": "minecraft:structure_void"
    },
    "result": {
        "item": "minecraft:jigsaw"
    },
    "experience": 0.1,
    "cookingtime": 200
}
```
This happened
![image](https://user-images.githubusercontent.com/16517352/185522922-c6b7290e-9270-48a5-a7eb-ff4814e959b5.png)

I know the syntax is wrong regardless, but it should probably not result in this ^^

**Comment by misode** [comment]
What is the expected result according to you?

**Comment by DorkOrc** [comment]
> What is the expected result according to you?

Just an empty string, or `result` just gets removed until something correct is written, not an invalid item object which gets displayed as `[object Object]`.

**Comment by misode** [comment]
Thinking about it further, I think this is probably good enough. I don't want to erase data when you import something.
