### ISSUE TITLE
Peaks & Valleys, and Humidity Noise are missing

### ISSUE THREAD

**Issue by BlendCreator** [misode/misode.github.io#286]
To generate Minecraft´s Terrain , 5 different Noises are used to achieve this: Contientalness, Erosion, Peaks & Valleys, Temperature and Humidity.
Contientalness, Erosion and Temerature are already there, but  Peaks & Valleys and Humidity are not there for some reason.

**Comment by misode** [comment]
Can you specify where exactly you think these are missing? In the noise router they are called vegetation and ridges.

**Comment by ApolloDatapacks** [comment]
> 5 different Noises are used to achieve this: Contientalness, Erosion, Peaks & Valleys, Temperature and Humidity.

These are not the five values. The five values used are Continentalness, Erosion, **Ridges** (called weirdness in dimension files), Temperature, and **Vegetation** (called humidity in dimension files)
