### ISSUE TITLE
Exclusion Zone in structure sets is supposed to be able to take more than 1 structure set

### ISSUE THREAD

**Issue by ApolloDatapacks** [misode/misode.github.io#287]
Attempting to add more than 1 structure set to an exclusion zone has unintended effects.
This is the JSON I put into the structure set generator:
![image](https://user-images.githubusercontent.com/102649729/188337981-21ab0170-3aa9-4ce2-a676-2895fde71260.png)
And this is the result:
![image](https://user-images.githubusercontent.com/102649729/188338009-9a80494b-b4df-40d6-adc3-317ede3afb4c.png)

**Comment by misode** [comment]
Have you verified in-game that this works?

**Comment by ApolloDatapacks** [comment]
Turns out I made a mistake, and it doesn't work. Minecraft didn't throw any errors so I assumed it worked lol
