### ISSUE TITLE
Structure set list and tag entry modes don't seem to work in 1.19.2

### ISSUE THREAD

**Issue by MattiDragon** [misode/misode.github.io#291]
Here are some example that are valid in the generator, but not ingame:
- https://misode.github.io/worldgen/structure-set/?share=a3978357-b877-4e96-ad89-28bd23f1ce69
- https://misode.github.io/worldgen/structure-set/?share=151b2e08-8e61-4d88-b2ab-ab5d2849c916
And here is a working one:
- https://misode.github.io/worldgen/structure-set/?share=348466be-1ef5-4834-960d-cd8529c2334e

Confused me when studying minecraft code and not finding how it handles those cases, turns out it doesn't, but an inline structure seems to work (based on code).

**Comment by misode** [comment]
Thanks for reporting this!
