### ISSUE TITLE
loot table preview went horribly wrong

### ISSUE THREAD

**Issue by FokaStudio** [misode/misode.github.io#298]
![image](https://user-images.githubusercontent.com/67797297/196762091-ef7d9818-24eb-48da-b99d-67567e15ec5d.png)
![image](https://user-images.githubusercontent.com/67797297/196762107-b3389830-081f-4a74-ab9d-c3fb66da21e4.png)

This has happened while using Google Chrome on Windows 10, if that was any helpful
just ask and I will provide you with far more info

**Comment by misode** [comment]
Was this a one off glitch or does this always happen and can you reproduce reliably?

**Comment by misode** [comment]
Okay I managed to reproduce it myself. I suspect this is because the UV mapping is cached but the atlas texture itself is not.

**Comment by misode** [comment]
As a temporary workaround, you should be able to fix this by clearing this cache (F12) for devtools, then to "Application" tab
![image](https://user-images.githubusercontent.com/17352009/196846145-7c0854c5-77a9-4300-a738-ec6e7cf36d03.png)

**Comment by misode** [comment]
I'm made a change that should fix this, but we'll have to wait until the next snapshot to confirm it.
