### ISSUE TITLE
Items with Count 0 can appear in preview when "Fill container randomly" is un-ticked

### ISSUE THREAD

**Issue by Bloo-dev** [misode/misode.github.io#303]
When the option "Fill container randomly" in the preview is **not** ticked, items with a count of 0 can appear in the preview. Note that these items do not show up when the option is ticked.

### How to Reproduce
1. Go to the [Loot Table Generator](https://misode.github.io/loot-table/).
2. Create a loot table that sets the `Count` of an item to `0`, e.g. [this Loot Table](https://misode.github.io/loot-table/?share=UD24oqyqkO).
3. Untick the option "Fill container randomly" in the preview settings.
4. An item with `Count:0` will appear in the preview.

![image](https://user-images.githubusercontent.com/41843855/201179392-23ac1879-3282-4c80-add4-3b8a99dcd6fe.png)

### Environment
This issue occurs no matter which Minecraft version is selected. Refreshing the preview does not fix the issue. The Count-0-item disappears if the "Fill container randomly" option is re-ticked.

Browser: Firefox 106.0.5 (64-bit)
Language: English
Darkmode

**Comment by misode** [comment]
This is now fixed, thanks for reporting!
