### ISSUE TITLE
Feature request support for the generator to add biomes and work out were they fit

### ISSUE THREAD

**Issue by Danjhop4** [misode/misode.github.io#308]
If you want to add a biome to let’s say the overworld you have to add it like 50 times and the game seems to use a package to generate the noise settings on the fly without storing the exact settings as far as I can tell one per biome could that be added to the site to allow easy to add surface biomes since adding it once only really seems to work for caves
Not got a feature request tag

**Comment by misode** [comment]
If you want to modify the overworld biome layout I recommend using Snowcapped: https://snowcapped.jacobsjo.eu/
