### ISSUE TITLE
Items from 1.19.3 are not recognised

### ISSUE THREAD

**Issue by IzukiKa** [misode/misode.github.io#314]
Items added in 1.19.3 are not recognised in the [loot table](https://misode.github.io/loot-table/) generator.
For instance [this ](https://misode.github.io/loot-table/?share=qpV4RatuvW) loot table says the item `minecraft:snow_golem_spawn_egg` does not exist when it, in fact, does exist.

**Comment by misode** [comment]
1.19.3 is a separate version in the dropdown. Though you make a good point, currently 1.19 is still set at the default, which I will change
![image](https://user-images.githubusercontent.com/17352009/209375843-da172899-b545-4947-821e-46914e2bf41b.png)
