### ISSUE TITLE
Loot table items with Object texts are italicized by default

### ISSUE THREAD

**Issue by EpyonProjects** [misode/misode.github.io#324]
When generating loot table items, the text is Italic by default using an Object in a set_name function.  Italic: False does not function properly.  Obfuscated also does not work, not sure if that was implemented.

The others work as expected (Bold, Underlined, Strikethrough)

![image](https://user-images.githubusercontent.com/66185010/213798250-fd1df280-b4d2-4895-8128-b17807a1c714.png)

**Comment by misode** [comment]
Obfuscated not working is "Won't fix" atm
