### ISSUE TITLE
Item icons Loot Table

### ISSUE THREAD

**Issue by Marshmachell** [misode/misode.github.io#326]
Item icons in loot tables are gone
![image](https://user-images.githubusercontent.com/110848187/214564137-806f19e0-b0bd-4d8a-be1e-48d891807077.png)

**Comment by misode** [comment]
@Marshmachell 
1. Could you open the console with `Ctrl+Shift+J` and check if there are any errors?
2. Could you check if `raw.githubusercontent.com` is blocked in your country, eg try this link: [diamond.png](https://raw.githubusercontent.com/misode/mcmeta/assets/assets/minecraft/textures/item/diamond.png)

**Comment by Marshmachell** [comment]
![image](https://user-images.githubusercontent.com/110848187/215115067-fdb74b96-94c6-4660-b8b0-81d2127a56e8.png)


> @Marshmachell
> 
> 1. Could you open the console with `Ctrl+Shift+J` and check if there are any errors?
> 2. Could you check if `raw.githubusercontent.com` is blocked in your country, eg try this link: [diamond.png](https://raw.githubusercontent.com/misode/mcmeta/assets/assets/minecraft/textures/item/diamond.png)

![image](https://user-images.githubusercontent.com/110848187/215115119-295ab1d0-97c0-4b02-b147-a6c05fd60d20.png)

**Comment by Marshmachell** [comment]
> @Marshmachell
> 
> 1. Could you open the console with `Ctrl+Shift+J` and check if there are any errors?
> 2. Could you check if `raw.githubusercontent.com` is blocked in your country, eg try this link: [diamond.png](https://raw.githubusercontent.com/misode/mcmeta/assets/assets/minecraft/textures/item/diamond.png)

![image](https://user-images.githubusercontent.com/110848187/215115166-44ba2cef-8433-4782-8235-ccddf7328f11.png)
link is working

**Comment by misode** [comment]
What OS and browser version are you using? Can you try another browser?

**Comment by Marshmachell** [comment]
> What OS and browser version are you using? Can you try another browser?

Windows 10, Google Chrome

**Comment by Marshmachell** [comment]
> What OS and browser version are you using? Can you try another browser?

![image](https://user-images.githubusercontent.com/110848187/215258107-869f9772-2869-402f-8661-22b82a962ba3.png)
I tried Microsoft Edge and it worked, but what about Google Chrome?

**Comment by Marshmachell** [comment]
> What OS and browser version are you using? Can you try another browser?

Bug fixed

**Comment by misode** [comment]
This seems to have been fix, and no one else has reported this issue since. I'm going to blame caching
