### ISSUE TITLE
Loot table preview tool missing attributes

### ISSUE THREAD

**Issue by EpyonProjects** [misode/misode.github.io#328]
Is having the attack damage and attack speed attribute tooltips for a tool a planned feature?
![image](https://user-images.githubusercontent.com/66185010/215128499-b829b74b-279b-42a9-8dd2-04941b916cbc.png)
![image](https://user-images.githubusercontent.com/66185010/215128566-63d89cbd-337f-4f54-8d7b-4df518725c1a.png)

**Comment by misode** [comment]
Fixed in fd6de2ac856ae4940141cda0d1a177b4ab51ad28

Note that due to implementation, this is only fixed in versions 1.21+
