### ISSUE TITLE
Error: Cannot get version "1.19": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.360b3ee5.js

### ISSUE THREAD

**Issue by rikupon12020** [misode/misode.github.io#339]
## Crash report
 * Page url: `https://misode.github.io/dimension/`
 * Generator ID: `dimension`
 * Current version: `1.19`
 * Latest version: `23w05a`

### Stack trace
```
Error: Cannot get version "1.19": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.360b3ee5.js
Error: Cannot get version "1.19": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.360b3ee5.js
    at (https://misode.github.io/assets/index.2999e3cc.js:31:33121)
```

### Generator JSON
<details>
<pre>
{
  "type": {
    "name": "minecraft:tutorial",
    "ultrawarm": false,
    "natural": true,
    "piglin_safe": true,
    "respawn_anchor_works": true,
    "bed_works": false,
    "has_raids": false,
    "has_skylight": true,
    "has_ceiling": false,
    "coordinate_scale": 1,
    "ambient_light": 0,
    "logical_height": 256,
    "infiniburn": "minecraft:infiniburn_overworld",
    "min_y": 0,
    "height": 256,
    "effects": "minecraft:overworld"
  },
  "generator": {
    "type": "minecraft:flat",
    "settings": {
      "layers": [
        {
          "block": "minecraft:grass_block",
          "height": 4
        },
        {
          "block": "minecraft:dirt",
          "height": 3
        },
        {
          "block": "minecraft:dirt",
          "height": 2
        },
        {
          "block": "minecraft:bedrock",
          "height": 1
        }
      ],
      "structures": {
        "structures": {}
      },
      "biome": "minecraft:the_void",
      "lakes": false,
      "features": false
    }
  }
}
</pre>
</details>

**Comment by misode** [comment]
I believe this can be fixed by simply reloading the page. This happens when you have a page open, and then a new build of the site is published. Not a lot I can do about this I fear.
