### ISSUE TITLE
Loot table "type" dropdowns are broken in 1.19.4

### ISSUE THREAD

**Issue by AjaxGb** [misode/misode.github.io#344]
If I go to https://misode.github.io/loot-table/ and change the version to 1.19.4, the dropdown that should let me select the type of an entry ("Item", "Group", "Alternatives", etc.) is empty. Clicking it shows a tiny box with no options inside it. If I add a function, or a condition, same thing. I can't select the type of function or condition. This also applies to Predicates and Item Modifiers. The only way to change the type is to manually edit it in the JSON display.

I am running the latest version of Firefox.

**Comment by AjaxGb** [comment]
![image](https://user-images.githubusercontent.com/7976377/219978536-eec97db4-bf32-41c9-9588-4a5d4cf93e94.png)

**Comment by DorkOrc** [comment]
This is not exclusive to "loot table type" dropdowns. Many dropdowns across the website don't work.
![image](https://user-images.githubusercontent.com/16517352/219981734-5302234f-ea75-47ce-9446-a2415fff9602.png)
![image](https://user-images.githubusercontent.com/16517352/219981757-fd8615ba-661a-49e6-9b47-82cefb045865.png)

**Comment by DorkOrc** [comment]
This is not an issue on Google Chrome. I am getting this error on Firefox.

**Comment by ApolloDatapacks** [comment]
Not an issue anymore
![image](https://user-images.githubusercontent.com/102649729/223627082-4800b4f9-5109-4a3d-bf39-ab183874aa0d.png)

**Comment by misode** [comment]
I believe this was temporarily caused by [MC-260030](https://bugs.mojang.com/browse/MC-260030), so not an issue the site could handle.
