### ISSUE TITLE
Transformation tool disappeared

### ISSUE THREAD

**Issue by Kimani8370** [misode/misode.github.io#347]
Not long ago I remember seeing a new transformation tool to obtain a preview of a transformed block_display entity. Now, selecting 1.19.4 version (also tested with Any) doesn't show this tool, maybe it got hidden after some update. Other 1.19.4 features, like armor trims and damage types are visible.

**Comment by misode** [comment]
It should be visible in the "Tools" section on the homepage https://misode.github.io/
