### ISSUE TITLE
please add snapshot worldgen to converter

### ISSUE THREAD

**Issue by Danjhop4** [misode/misode.github.io#352]
if a setting needs a default just set it to false or what ever base value it needs to fast update a pack like to make a 1.19.3 pack work in 1.19.4 or snapshots like downloaded packs

**Comment by misode** [comment]
If you paste a file in the generator is doesn't auto-fill any fields. This is intentional so you can use it as a validator. Just make any change in the visual editor and it will auto-fix most fields.
