### ISSUE TITLE
Inline structure overrides in flat level generation presets don't work ingame

### ISSUE THREAD

**Issue by sme23** [misode/misode.github.io#355]
Tool allows for defining inline structure sets in flat level generation presets, but if a preset is loaded ingame with inline structure sets it breaks structure overrides entirely. Everything works fine with a reference instead of it being inline, probably a bug on Mojang's part but this still probably shouldn't let you make them inline here when it doesn't work

**Comment by sme23** [comment]
Sorry for late response. Here's 2 datapacks that add ancient cities underneath a superflat world, one with the structure set inline and the other with it as a separate file. In the inline version, the spacing & separation is ignored and there are an excessive number of ancient cities below the world. In the reference version, the spacing & separation is respected and they are quite rare.
[ancient_cities_superflat_inline.zip](https://github.com/misode/misode.github.io/files/11536049/ancient_cities_superflat_inline.zip)
[ancient_cities_superflat_reference.zip](https://github.com/misode/misode.github.io/files/11536050/ancient_cities_superflat_reference.zip)

**Comment by misode** [comment]
Fixed in 88d15173a0b3f9844abbb09fd3819577256535e5. Thank you for the report!
