### ISSUE TITLE
Error: Cannot get version "1.19.4": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.fbd28087.js

### ISSUE THREAD

**Issue by Danjhop4** [misode/misode.github.io#357]
## Crash report
 * Page url: `https://misode.github.io/worldgen/feature/`
 * Generator ID: `worldgen/configured_feature`
 * Current version: `1.19.4`
 * Latest version: `1.19.4-rc1`

### Stack trace
```
Error: Cannot get version "1.19.4": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.fbd28087.js
Error: Cannot get version "1.19.4": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.fbd28087.js
    at (https://misode.github.io/assets/index.4ee7698b.js:135:35132)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:tree",
  "config": {
    "minimum_size": {
      "type": "minecraft:two_layers_feature_size"
    },
    "dirt_provider": {
      "type": "minecraft:simple_state_provider",
      "state": {
        "Name": "minecraft:stone"
      }
    },
    "trunk_provider": {
      "type": "minecraft:simple_state_provider",
      "state": {
        "Name": "minecraft:stone"
      }
    },
    "foliage_provider": {
      "type": "minecraft:simple_state_provider",
      "state": {
        "Name": "minecraft:stone"
      }
    },
    "trunk_placer": {
      "type": "minecraft:straight_trunk_placer",
      "base_height": 5,
      "height_rand_a": 2,
      "height_rand_b": 0
    },
    "foliage_placer": {
      "type": "minecraft:blob_foliage_placer",
      "radius": 2,
      "offset": 0,
      "height": 3
    },
    "decorators": [
      {
        "type": "minecraft:attached_to_leaves",
        "probability": 0,
        "exclusion_radius_xz": 0,
        "exclusion_radius_y": 0,
        "required_empty_blocks": 1,
        "block_provider": {
          "type": "minecraft:simple_state_provider",
          "state": {
            "Name": "minecraft:stone"
          }
        },
        "directions": []
      }
    ]
  }
}
</pre>
</details>

**Comment by Danjhop4** [comment]
tried swaping from 1.19.3 to 1.19.4

**Comment by misode** [comment]
Usually this error happens when a new site update it pushed and you're still on the old build. There are probably solutions for this.
