### ISSUE TITLE
Error rendering the tree: Cannot read properties of undefined (reading 'enabled')

### ISSUE THREAD

**Issue by drathmorgh** [misode/misode.github.io#358]
## Crash report
 * Page url: `https://villagerconfig.vercel.app/villagerconfig/`
 * Generator ID: `villagerconfig`
 * Current version: `1.19`
 * Latest version: ``

### Generator JSON
<details>
<pre>
{
  "tiers": [
    {
      "total_exp_required": 0,
      "groups": [
        {
          "num_to_select": 2,
          "trades": [
            {
              "cost_a": {
                "type": "minecraft:item",
                "name": "minecraft:bow",
                "functions": [
                  {
                    "function": "minecraft:set_name",
                    "count": 1
                  }
                ]
              },
              "result": {
                "type": "minecraft:item",
                "name": "minecraft:stone"
              },
              "trader_experience": 0
            }
          ]
        }
      ],
      "rolls": 1
    }
  ]
}
</pre>
</details>

tested in the 1.19 and 1.19.3 version. 

I have set the result to be a bow first before trying to use the set name function and I get this error.. 
I have tried to name a few other blocks and items and as soon as "set name" is clicked I get the error.
In this example the result is stone. but I can confirm that it is acting the same for bow, stone, trident, and crossbow. I didn't try any more items as it seemed conclusive enough. 
![image](https://user-images.githubusercontent.com/81181296/227060343-608e485e-9a8f-46dc-bb3d-c05d8dae4757.png)

**Comment by ApolloDatapacks** [comment]
Villagerconfig isn't maintained by Misode to my knowledge, whoever maintains it should receive the bug report as there's nothing here that can be done to fix it

**Comment by misode** [comment]
If you can reproduce this bug on misode.github.io, feel free to add a comment here or create a new issue.
