### ISSUE TITLE
SyntaxError: Something went wrong rendering the generator: Something went wrong rendering the generator: Expected ',' or '}' after property value in JSON at position 21

### ISSUE THREAD

**Issue by Manasukiyami-Github2** [misode/misode.github.io#359]
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.19.4`
 * Latest version: `1.19.4`

### Stack trace
```
SyntaxError: Something went wrong rendering the generator: Something went wrong rendering the generator: Expected ',' or '}' after property value in JSON at position 21
    at JSON.parse (<anonymous>)
    at parse (src/app/components/ItemTooltip.tsx:29:33)
    at ur.I8 (../../node_modules/preact/dist/preact.module.js:1:8150)
    at Fc (../../node_modules/preact/dist/preact.module.js:1:5862)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
    at j (../../node_modules/preact/dist/preact.module.js:1:2129)
    at w (../../node_modules/preact/dist/preact.module.js:1:7348)
    at L (../../node_modules/preact/dist/preact.module.js:1:6312)
```

### Generator JSON
<details>
<pre>
{
  "pools": [
    {
      "rolls": {
        "min": 8,
        "max": 15
      },
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:golden_apple",
          "functions": [
            {
              "function": "minecraft:set_nbt",
              "tag": "{display:{Name:'[{\"text\":\"Birch Apple\":\"color\":\"yellow\",\"italic\":false}]'}}",
              "count": 1
            },
            {
              "function": "minecraft:set_count",
              "count": {
                "min": 1,
                "max": 5
              },
              "add": false
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:birch_wood",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": {
                "min": 3,
                "max": 5
              }
            }
          ]
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment]
The item preview now won't freak out, but it's worth nothing that this was caused by an incorrect display name JSON. In you case:
`'[{\"text\":\"Birch Apple\":\"color\":\"yellow\",\"italic\":false}]'`
->
`'[{\"text\":\"Birch Apple\",\"color\":\"yellow\",\"italic\":false}]'`
