### ISSUE TITLE
Can you support this mod adds new worldgen types 

### ISSUE THREAD

**Issue by Danjhop4** [misode/misode.github.io#362]
This mod adds new types of world gen options like the one to add layers to feature like dripstone then a ore feature to replace the dripstone something normal mc can’t do

**Comment by Danjhop4** [comment]
https://github.com/jack-zisa/CreoLib/

**Comment by misode** [comment]
If someone wants to they are free to add customized generators supporting this mod, but this is not in scope for the schemas.
