### ISSUE TITLE
Cannot find generator "/assets/medel/?version=1.19.4"

### ISSUE THREAD

**Issue by lovise5** [misode/misode.github.io#377]
## Crash report
 * Page url: `https://misode.github.io/assets/medel/?version=1.19.4`
 * Current version: `1.19.4`
 * Latest version: `1.20-pre1`

**Comment by misode** [comment]
Your URL seems to have a typo in it. It should be https://misode.github.io/assets/model/?version=1.19.4

@lovise5 How did you find yourself on this URL?
