### ISSUE TITLE
Cannot find generator Faction Generator

### ISSUE THREAD

**Issue by BambiMann** [misode/misode.github.io#378]
## Crash report
 * Page url: `https://misode-git-fork-patrigan-master-misode.vercel.app/partners/factioncraft/`
 * Current version: `1.19`
 * Latest version: ``

**Comment by misode** [comment]
Forks are not supported on this issue tracker, however a quick look tells me you were probably looking for this like: https://misode-git-fork-patrigan-master-misode.vercel.app/partners/faction-craft/faction/
