### ISSUE TITLE
Preview Breaks When Using a Block Outside of Predefined List

### ISSUE THREAD

**Issue by Darkosto** [misode/misode.github.io#379]
Hello!

When using the Noise Settings Generator, the preview will break when using a block outside of this list: https://github.com/misode/misode.github.io/blob/97e996191993899a3bc0e858418dd5c062bd20a1/src/app/components/previews/NoiseSettingsPreview.tsx#LL108C7-L108C18

The preview window will go completely gray until that block is removed from the generation: 

![image](https://github.com/misode/misode.github.io/assets/10309699/84b0d51d-1db3-4fbf-9d89-ae391aea8b17)

I believe this happened when PR #322 was merged

Prior to this PR, any block not found on the list would be rendered black.

Thank you!

**Comment by misode** [comment]
@Darkosto Thank you for spotting this and for the report! It has now been fixed!
