### ISSUE TITLE
Visulaizer for a multi noise dimension breaks

### ISSUE THREAD

**Issue by kruthers** [misode/misode.github.io#388]
### Bug Descriptiuon
On https://misode.github.io/dimension/  using mutli noise the preview fails to render

## What i get

Only one colour showing and an exception in console
```
Uncaught TypeError: can't assign to property "biome" on "minecraft:desert": not an object
    set DataModel.js:140
    validate ObjectNode.js:95
    validate ObjectNode.js:82
    validate Reference.js:36
    h ListNode.js:49
    validate ListNode.js:48
    validate ObjectNode.js:86
    validate ObjectNode.js:82
    validate ObjectNode.js:86
    validate ObjectNode.js:82
    validate ObjectNode.js:86
    validate ObjectNode.js:82
    validate DataModel.js:179
    set DataModel.js:147
    l renderHtml.tsx:415
    Qu Preact
```

## What i expect

It to show an example of the world generator

## How to reproduce

1. Go to https://misode.github.io/dimension/ 
2. Set Dimension type to `minecraft:overworld`
3. Set Generator to `Default`
4. Set Biome source to `Multi noise`
5. Set Biomes preset to `Unset`
6. Add another biome so there is 2

## Enviroment

- Firefox Version 114.0.1

**Comment by misode** [comment]
I managed to figure out that this happens when you switch from the checkerboard type to the multi noise type.
