### ISSUE TITLE
Cannot load preset acacia in 1.19.4

### ISSUE THREAD

**Issue by CodeCraftPlugin** [misode/misode.github.io#402]
## Crash report
 * Page url: `https://misode.github.io/worldgen/feature/?version=1.19.4`
 * Generator ID: `worldgen/configured_feature`
 * Current version: `1.19.4`
 * Latest version: `1.20.1`

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:random_patch",
  "config": {}
}
</pre>
</details>
this is with every preset

**Comment by misode** [comment]
Duplicate of #360
