### ISSUE TITLE
Recipe Generator is missing categories

### ISSUE THREAD

**Issue by TelepathicGrunt** [misode/misode.github.io#404]
If you check the Acacia Chest Boat recipe, it contains `"category": "misc",` to put recipe in right place in recipe book.
https://github.com/misode/mcmeta/blob/data-json/data/minecraft/recipes/acacia_chest_boat.json
![image](https://github.com/misode/misode.github.io/assets/40846040/8df2deb2-3f47-4577-8619-a655bc7ff48b)

However, the recipe generator site set to 1.20 will not show the category for the same recipe
https://misode.github.io/recipe/?version=1.20&preset=acacia_chest_boat
![image](https://github.com/misode/misode.github.io/assets/40846040/d161bfda-1a05-49c8-b781-fea6de971d99)

**Comment by misode** [comment]
Fixed in https://github.com/misode/minecraft-schemas/commit/fdbcf35e2a2c9b7e5c4e40cd0a3f74c4d4af9869. For now I have one list of options, even though some options are only allowed in crafting and some only in smelting. There may be room for improvement in the future.
