### ISSUE TITLE
Sound Explorer does not add linebreaks after generated commands

### ISSUE THREAD

**Issue by Rubbli** [misode/misode.github.io#407]
There are no linebreaks in the downloadable file.
Here is a freshly downloaded file with the extention changed from .mcfunction to .txt to be able to upload it to github.
[sounds(2).txt](https://github.com/misode/misode.github.io/files/12210258/sounds.2.txt)

**Comment by misode** [comment]
I cannot reproduce the issue. I get linebreaks as intended.
