### ISSUE TITLE
Add ability to create new files

### ISSUE THREAD

**Issue by Scroogeee** [misode/misode.github.io#411]
Perhaps I am missing something obvious, but what I am really missing is a way to create additional files while editing a pack on the website. That way, there would be no more need to constantly download, manually add a file, zip everything and reupload the whole project.

It could look something like this from the drop down menu:
<img width="309" alt="Bildschirmfoto 2023-08-14 um 22 04 26" src="https://github.com/misode/misode.github.io/assets/30441849/03d46f2a-3757-4d92-83fd-ae8cf1a972ea">

or something like this if invoked by the context menu (right clicking on any file/folder in the hierarchy)
<img width="309" alt="Bildschirmfoto 2023-08-14 um 22 03 52" src="https://github.com/misode/misode.github.io/assets/30441849/ce87169b-26d9-47fa-9b7b-865a36a1bb88">

**Comment by Fennecai** [comment]
yes! this would be very helpful.

**Comment by Fennecai** [comment]
yes, since saving the current file as something different is pretty unwieldy, especially if you want to make a new file for something that isnt the same kind of thing was what the current file is (like a new dimension when i just was editing a biome for instance)

**Comment by Scroogeee** [comment]
There actually seems to be a simpler workflow:

- Save your current_work.json
- Switch to the desired generator for the new file
_- Optional: Begin editing_
- Actually save as a new file
- Continue editing

**Comment by Fennecai** [comment]
that actually doesnt work Scroogeee, if you change the current file at all that is intuitively auto-saved in that file even when you save it as a different file and go back to it it'll have the changes you made prior to manually saving it as a different file and you'll lose your work.

**Comment by Scroogeee** [comment]
Perhaps I didn't explain myself properly. If you want to have the same generator, you have to save as new file **before** you make any changes. At least that's how it seems to work when I use it. Still I agree that this is quite unintuitive.

**Comment by misode** [comment]
This has been implemented in this dropdown:
![image](https://github.com/misode/misode.github.io/assets/17352009/103c3c95-acba-4655-8f80-33c6badea9ab)
