### ISSUE TITLE
Splines are undocumented

### ISSUE THREAD

**Issue by Treeway7** [misode/misode.github.io#414]
On the page "[How terrain is generated using the noise router](https://misode.github.io/guides/noise-router/?version=1.19)", the section about splines is undocumented.

![image](https://github.com/misode/misode.github.io/assets/56928485/463b4cb6-1eaa-42d8-be2b-0f7317fdfa93)

**Comment by misode** [comment]
This is not a bug, sadly I haven't had time to work in it.
