### ISSUE TITLE
Performance issue in Noise Settings Generator

### ISSUE THREAD

**Issue by SlendySWIRS** [misode/misode.github.io#416]
Hi!
I'm not sure if this is the correct place for my issue and/or if this has been discussed before so please bear with me.
The problem I'm currently having is about performance in noise settings (with the display open): most of the time, dragging or scrolling (zooming) on the display cause almost the entire page to freeze for a couple of seconds (and by almost I mean all control over the settings, the display and the cursor, apart from the ability to scroll through the settings list, which still works fine). The duration depends on the exact settings, for example putting everything in the "noise router" part to a constant 0, apart from final density on End islands (inline) has a way worse performance than final density on interpolated overworld base 3d noise (as a reference).
I checked this on both firefox and chrome and the freeze happens in both browsers. I also checked the running proccesses for the memory and CPU load and it seems like the generator uses 100% of the CPU during these moments (although task manager says only 10% of the cpu is used altogether?). I was wondering if
1) this is something that other people encounter as well
2) this is normal and unavoidable
3) this is due to insufficient specs
4) this is caused by unoptimized browser settings

Sorry in advance if I should've used an issue template of some kind, be sure to let me know and I'll edit this to follow the guidelines :)

**Comment by misode** [comment]
You're right, noise settings take a long time to simulate. Especially the end islands. Atm though there is nothing I can do to remidy this.

**Comment by misode** [comment]
Not planning any performance improvements atm :/
