### ISSUE TITLE
Some items from some entries are appearing in the loot_table

### ISSUE THREAD

**Issue by chawdan** [misode/misode.github.io#432]
<img width="253" alt="image" src="https://github.com/misode/misode.github.io/assets/44719435/116897cf-45bb-4786-9dbc-03d34e222660">

<img width="185" alt="image" src="https://github.com/misode/misode.github.io/assets/44719435/7e1dcca8-e812-453b-82ff-2b2c2a949e28">

In these screenshots, I am using the wither skeleton skull preset

**Comment by misode** [comment]
Duplicate of #301
