### ISSUE TITLE
Several missing registry tag types

### ISSUE THREAD

**Issue by DorkOrc** [misode/misode.github.io#434]
There are several missing tag file generators:
- `banner_pattern`
- `cat_variant`
- **`damage_type`**
- `instrument`
- `painting_variant`
- `point_of_interest_type`

While a few of these are limited in what they can be used for in-game, it would still be valuable to have generators for them offered, especially for the purpose of validating a handwritten tag.

Of all the tag types listed, the main one I personally find myself wanting is **`damage_type`**, and I believe that that one is something that should be prioritised as it has lots of uses throughout data packs.

**Comment by Apollounknowndev** [comment]
Since you can make tags for *any* registry, I think it'd be better to merge all of the tag generators into one generator with a `registry` field.

**Comment by misode** [comment]
> Since you can make tags for any registry, I think it'd be better to merge all of the tag generators into one generator with a registry field.

That would be ideal but a bit tricky to implement, especially integrating it with projects on the site. I think I'm just going to add all the useful tags.
