### ISSUE TITLE
Loot table item tag missing required argument

### ISSUE THREAD

**Issue by Kimani8370** [misode/misode.github.io#435]
In the loot table generator, if Entry type is set to `Item tag` (`tag`), the `Expand` field is required (tested in 1.20.2). If not specified, the loot table will fail on invoke. I suggest setting this field to mandatory (same way as, for example, the `Item tag name` field in the same Entry configuration).

**Comment by misode** [comment]
This has been fixed in https://github.com/misode/minecraft-schemas/commit/d812fd8bd332062c9b8c122ad235b1e399fd0e1f, thank you for the report!
