### ISSUE TITLE
Particle type `falling_dust` in Biome Generator is missing options

### ISSUE THREAD

**Issue by UnknownSilicon** [misode/misode.github.io#438]
According to the Minecraft Wiki, the `falling_dust` type, along with `block` and `block_marker`, should have a parameter for the block state used for the particle.

https://minecraft.fandom.com/wiki/Custom_biome

![image](https://github.com/misode/misode.github.io/assets/14339279/72b6b125-e21a-44a2-8e0d-35f18065e518)

**Comment by misode** [comment]
Particle types were recently added to the generator, this should be fixed.
