### ISSUE TITLE
Cannot load preset acacia_fence in 1.20

### ISSUE THREAD

**Issue by Axiumyuyu** [misode/misode.github.io#439]
## Crash report
 * Page url: `https://misode.github.io/recipe/?version=1.20`
 * Generator ID: `recipe`
 * Current version: `1.20`
 * Latest version: `23w40a`

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:crafting_shaped",
  "pattern": [],
  "key": {},
  "result": {
    "item": "minecraft:stone"
  }
}
</pre>
</details>

**Comment by misode** [comment]
Duplicate of #360
