### ISSUE TITLE
[Enhancement] Allow for typing in the search bar without having to navigate to the search bar

### ISSUE THREAD

**Issue by DorkOrc** [misode/misode.github.io#443]
As many other websites with lots of options/menus do, allowing the user to immediately start typing into the search box upon loading the page (without having to click "All Generators" then clicking the search bar) would streamline using the app significantly.

Typing outside the search box currently has no other purpose, so opening the page and immediately being able to type, say "item m"+tab to open the Item Modifiers generator, would be lovely.

**Comment by misode** [comment]
Thank you for the suggestion, this was easy to implement!
