### ISSUE TITLE
[Enhancement] Adding Terrain Profile Preview to Dimension Generator

### ISSUE THREAD

**Issue by Jaffe2718** [misode/misode.github.io#444]
It is not enough to have a bird's eye view preview of the noise layer and biomes. Because it is difficult to blindly write noise rules in Dimension Generator without knowing how the terrain profile is generated, it would be easier to write noise rules while rendering and previewing the terrain profile when creating custom dimensions.

**Comment by misode** [comment]
@Jaffe2718 I'm not completely sure what you mean with this. What do you want visualized when you are editing which file?

**Comment by Jaffe2718** [comment]
> @Jaffe2718 I'm not completely sure what you mean with this. What do you want visualized when you are editing which file?

the json file which define a custom dimension

**Comment by misode** [comment]
Sorry, but that doesn't tell me anything. There is already a biome layout visualizer on the dimension page, and a terrain side view on the noise settings page. What is the thing that these two don't cover?

![image](https://github.com/misode/misode.github.io/assets/17352009/b89e7781-9a3e-44f1-b05a-c7f0eb1fec73)
![image](https://github.com/misode/misode.github.io/assets/17352009/2490d0be-8a68-4e64-aa01-45343fed8246)

**Comment by misode** [comment]
Closing because this is already implemented
