### ISSUE TITLE
Predicate generator needs a fix with block state output

### ISSUE THREAD

**Issue by neeeekolaz** [misode/misode.github.io#451]
Hello, thanks for all your generators, I use them so frequently.

Tonight I noticed that it does not output block state values in predicates properly.

Please see https://bugs.mojang.com/browse/MC-264739
which was resolved with the below comment:

"Thank you for this report! This was not originally an intentional change, however after investigation and discussion, we are closing this as intended behaviour. We will be including a note in the release changelog for 1.20.2, as it is of course a breaking change.

To elaborate on motivations: this behaviour previously worked somewhat 'accidentally', but the intended encoding was always to use quoted strings. This is consistent with how block states are encoded in other parts of the game. This is particularly relevant when encoding block states as NBT, as there is no distinction in data between a boolean and byte - which means that knowledge of the block type is required to parse the state (this is not always available)."

Thanks!

**Comment by misode** [comment]
This was fixed in https://github.com/misode/minecraft-schemas/commit/21df618aa02473b8addf59ced76c965a335843e9, thanks for reporting!
