### ISSUE TITLE
The "Overlays" field in the pack.mcmeta generator is wrong

### ISSUE THREAD

**Issue by DorkOrc** [misode/misode.github.io#456]
Each object in the `overlays.entries` list should contain `formats` and `directory`, not `namespace` and `path`. This results in an invalid output and overlays from imported files get deleted.

![image](https://github.com/misode/misode.github.io/assets/16517352/d3ef549c-752a-4bc7-8ac2-765a4d713bd5)

An example of a valid `pack.mcmeta` file which when imported gets its overlays deleted:
```
{
	"pack": {
		"description": "hello world",
		"pack_format": 18,
		"supported_formats": {
			"min_inclusive": 18,
			"max_inclusive": 29
		}
	},
	"overlays": {
		"entries": [
			{
				"formats": {
					"min_inclusive": 19,
					"max_inclusive": 29
				},
				"directory": "format_19"
			}
		]
	}
}
```

**Comment by misode** [comment]
This was fixed in https://github.com/misode/minecraft-schemas/commit/7a83cc5dc3043c41b1281c9264d82097a4f5fc9c, thanks for reporting!
