### ISSUE TITLE
1.20+ Add key "item" for "placed_block" advancement

### ISSUE THREAD

**Issue by FunkyToc** [misode/misode.github.io#461]
With 1.20+, the key "item" suddenly disapears from misode generator. But it still works in game, and is very usefull to detect wich item has been used when placing the block.

`
{
  "criteria": {
    "placed_ladder": {
      "trigger": "minecraft:placed_block",
      "conditions": {
      	"item": {
	  "item": "minecraft:ladder"
	},
	"location": [
          {
            "condition": "minecraft:entity_properties",
            "entity": "this"
          }
        ]
      }
    }
  },
  "rewards": {
    "function": "nm:my_function"
  }
}
`

Note that the "location" part is required between 1.20 and 1.20.2. With 1.20.3+, leaving this blank is ok.

**Comment by misode** [comment]
This was a breaking change made in 1.20, you need to update your advancements: <https://misode.github.io/versions/?id=23w18a&tab=changelog&search=trigger>
