### ISSUE TITLE
Major Version snapshot changes

### ISSUE THREAD

**Issue by Daniel99j2** [misode/misode.github.io#465]
In https://misode.github.io/versions/, Technical Changes, Fixed Bugs, and McMeta Diff should have a new section underneath each of them, that contains all the changes in the previous snapshots (Newer snapshots should override older ones).
This would be useful to know all changes to a major release, as currently you have to look at the snapshots individually.

**Comment by Daniel99j2** [comment]
* For non-snapshot or prerelease versions

**Comment by misode** [comment]
I believe this is already the case. Version pages like https://misode.github.io/versions/?id=1.20.2 already show a list of changes from all of its snapshots.

**Comment by Daniel99j2** [comment]
🤦
