### ISSUE TITLE
1.20.3-1.20.4 Advancement Generator Still Allows Non-String Block State Entries

### ISSUE THREAD

**Issue by Bloo-dev** [misode/misode.github.io#466]
### What's Wrong?
Ever since Minecraft 1.20.3\* block states in advancements and predicates must always be evaluated as strings, not booleans.

\* Verification needed. I couldn't find it on the technical changelog but do remember seeing it a in a slicedlime technical changelog video
### How does this effect the website?
As a result, an advancement or predicate checking for a black with a state `powered=false` but written in advancements (e.g. in a `location_check` condition) as
```
"state": {
"powered": false
}
```
will always fail. Instead the Advancement must be written as
```
"state": {
"powered": "false"
}
```

From the minecraft F3 screen it is not clear that all block states shall always be treated as strings, especially not since `true` and `false` actually get colored green and red accordingly.

### How can this be solved?
The generators on the website should not offer the option to set a type for block states if the selected version is 1.20.3-1.20.4, as they are always strings.

**Comment by misode** [comment]
This was fixed in https://github.com/misode/minecraft-schemas/commit/21df618aa02473b8addf59ced76c965a335843e9, thanks for reporting!
