### ISSUE TITLE
1.20.4 not working, pack version 26 doesnt seem to be supported

### ISSUE THREAD

**Issue by LadyHaley** [misode/misode.github.io#472]
It keeps outputting pack version 15, when I tried putting an up to date pack to see what happens, this is what I get
`No matching version found for pack format 26, using fallback 1.20
Cannot parse file "data/blazeandcave/advancements/adventure/i_just_want_to_make_toast.json": JSON.parse: bad escaped character at line 22 column 30 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/adventure/nerds_never_die.json": JSON.parse: bad escaped character at line 24 column 30 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/adventure/nyan_sheep.json": JSON.parse: bad escaped character at line 22 column 30 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/adventure/slenderman.json": JSON.parse: bad escaped character at line 21 column 27 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/adventure/the_one_and_true_johnny.json": JSON.parse: bad escaped character at line 21 column 27 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/adventure/whats_up_doc.json": JSON.parse: bad escaped character at line 23 column 30 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/enchanting/god_of_thunder.json": JSON.parse: bad escaped character at line 24 column 31 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/enchanting/ill_be_back.json": JSON.parse: bad escaped character at line 23 column 31 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/enchanting/this_name_sounds_cooler.json": JSON.parse: bad escaped character at line 23 column 31 of the JSON data.
Cannot parse file "data/blazeandcave/advancements/end/organizational_wizard.json": JSON.parse: bad escaped character at line 21 column 31 of the JSON data.`

**Comment by misode** [comment]
This looks like errors from the "Data-pack helper plus" vscode extension, did you meant to report a bug there?
