### ISSUE TITLE
The function "Set enchantments" doesn't accurately display an example for books

### ISSUE THREAD

**Issue by Tholleman** [misode/misode.github.io#473]
Take the following loot table example:
```json
{
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:book",
          "functions": [
            {
              "function": "minecraft:set_enchantments",
              "enchantments": {
                "minecraft:lure": 3
              }
            }
          ]
        }
      ]
    }
  ]
}
```
In Minecraft, this will generate an enchanted book with Lure III as a stored enchantment.
The example item in the generator creates a glowing book. It probably gives the book an nbt with `{Enchantments:[{id:"minecraft:lure",lvl:3}]}` instead of `{StoredEnchantments:[{id:"minecraft:lure",lvl:3}]}`. That would be correct for other items but books are a special case.

**Comment by misode** [comment]
Fixed infd6de2ac856ae4940141cda0d1a177b4ab51ad28
