### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by davidromrell** [misode/misode.github.io#478]
Can you try to get Open Terrain Generator (OTG) to update for newer versions? Note a category that would be good to add is NBT and craftTweaker as a page (support the base pages instead of spending a load of time on use cases). Thanks.

**Comment by misode** [comment]
Could you provide some links or examples for what you're after? It's not immediately clear to me.

**Comment by davidromrell** [comment]
support craft tweakers "the entirely new blocks and items" and "change item properties" and (support their custom nbt).

**Comment by misode** [comment]
Unless you give me a link or json example I don't think I can help.
