### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by zangyma** [misode/misode.github.io#479]
I once tried to package it into a Docker image by myself, but failed. If possible, could you provide a docker-compose.yml file? This way, I can run it locally. It's a bit difficult for me to access GitHub.

If you could provide a docker-compose configuration file, that would be great. I'm not sure how much work it involves, but I'm willing to help out. However, my attempts so far have been unprofessional and resulted in various errors.       ^.^

**Comment by misode** [comment]
You can clone or download the repository locally and build it with Vite. I don't have much experience with Docker so that seems unlikely to happen. PWA support is tracked in #227
