### ISSUE TITLE
Cannot find generator "/%C3%A3%C2%80%C2%80%C3%A4%C2%BD%C2%9C%C3%A8%C2%80%C2%85"

### ISSUE THREAD

**Issue by YokobYukkuri** [misode/misode.github.io#480]
## Crash report
 * Page url: `https://misode.github.io/%C3%A3%C2%80%C2%80%C3%A4%C2%BD%C2%9C%C3%A8%C2%80%C2%85`
 * Current version: `1.20.3`
 * Latest version: `24w09a`

**Comment by misode** [comment]
Where did you find this link? What brought you to the site?
