### ISSUE TITLE
What is Obsidian?

### ISSUE THREAD

**Issue by Glowing0v3rlord** [misode/misode.github.io#494]
I'm seeing generators for Obsidian Item and Obsidian Block in the modded generators list, but I can't find any mods that relate to that. Can anyone tell me what that is?

**Comment by misode** [comment]
It is a mod made by @oliviathevampire, I don't know much more about it

**Comment by fenziie** [comment]
God damn, im so glad I could find this. That is so damn cool.

**Comment by oliviathevampire** [comment]
> God damn, im so glad I could find this. That is so damn cool.

thank you!
