### ISSUE TITLE
Save As overwrites opened recipe

### ISSUE THREAD

**Issue by silicondev** [misode/misode.github.io#500]
When modifying a saved recipe, and saving as a new name. The opened file also gets overwritten with the changes.

Reproduce:
1. Create a new recipe and name it 'A'
2. Open recipe 'A' and make any change.
3. Save the changed recipe as 'B'.
recipe 'B' will be created with the new recipe, but recipe 'A' has also retained the changes.

**Comment by alex89912** [comment]
the bug is still open?

**Comment by misode** [comment]
This is intended. Files auto-save. The workaround is to first make a copy of the current file and then make the changes in the new file.
