### ISSUE TITLE
Components `custom_data`, `entity_data` and `block_entity_data` cannot specify custom fields

### ISSUE THREAD

**Issue by Bowswa** [misode/misode.github.io#507]
I know this is probably planned already, but i didn't see an issue for it. Custom Data editor, with an example default for the format would be amazing!

**Comment by misode** [comment]
This is currently a limitation with the schema framework. I don't have an immidiate fix for this, but I'm aware this is an issue.

**Comment by Yu-Hayate** [comment]
hmm, idk how custom items are made in loot tables and stuff, but if you can use a /give command as input then ig that it would work? im not sure at all, i dont know how to make loot tables

**Comment by CharlieThunkman** [comment]
In the online editor, could you store the text into session storage? The linked example is for a JavaScript extension called P5.js, but there is native functionality that I'm using for another project. https://www.youtu.be/_SRS8b4LcZ8

**Comment by Bowswa** [comment]
I've seen this issue has been slowly improved. However, I have an idea to improve the "custom_data" problem. I understand that the string is allowed, but an object cannot be handled. 
Could you add support for at least a boolean piece of data? This could be the base for even more custom data.
I would do a option box to include "boolean", and the ability to add a boolean data. The data would require being named from a text input, and have a "true false" toggle. 

After that you would have somewhere to do more work on this issue.

This is just a suggestion on how to make more progress. Use at will!
