### ISSUE TITLE
Item Modifier Set Components function doesn't work for lodestone_tracker

### ISSUE THREAD

**Issue by Pacca64** [misode/misode.github.io#520]
The format for the minecraft:lodestone_tracker item component is not correct in the Item Modifier Set Components function, which causes all the information put in the generator for the component to be discarded after the component is set, which makes the compass spin wildly in all circumstances, even if the user set valid a valid position and dimension.

This is what the generator currently outputs:
`[
  {
    "function": "minecraft:set_components",
    "components": {
      "minecraft:lodestone_tracker": {
        "tracker": {
          "dimension": "minecraft:overworld",
          "pos": [
            290,
            0,
            290
          ]
        },
        "tracked": false
      }
    }
  }
]`

And this is what a functional output looks like:
`[
  {
    "function": "minecraft:set_components",
    "components": {
      "minecraft:lodestone_tracker": {
        "target": {
          "dimension": "minecraft:overworld",
          "pos": [
            290,
            0,
            290
          ]
        },
        "tracked": false
      }
    }
  }
]`

tested in 1.20.6 and 24w20a

**Comment by misode** [comment]
Thank you for reporting this issue, it has been fixed!
