### ISSUE TITLE
`recipe` should be `result` in 24w10a 

### ISSUE THREAD

**Issue by Endernice61** [misode/misode.github.io#521]
It says "Changed recipe types `smelting`, `blasting`, `smoking`, and `campfire_cooking`. The `recipe` field is now an object with fields `id` (item resource location) and `components` (component patch map)."
when it should say "Changed recipe types `smelting`, `blasting`, `smoking`, and `campfire_cooking`. The `result` field is now an object with fields `id` (item resource location) and `components` (component patch map)."

**Comment by misode** [comment]
Thanks for noticing, it's been fixed!
