### ISSUE TITLE
Cannot load preset entities/villager in 1.20

### ISSUE THREAD

**Issue by markthasher** [misode/misode.github.io#525]
## Crash report
 * Page url: `https://misode.github.io/loot-table/?version=1.20`
 * Generator ID: `loot_table`
 * Current version: `1.20`
 * Latest version: `24w20a`

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:advancement_entity"
}
</pre>
</details>

**Comment by misode** [comment]
Duplicate of #360
