### ISSUE TITLE
None of the presets for advancements, loot tables, or recipes are loading

### ISSUE THREAD

**Issue by zalnimations** [misode/misode.github.io#528]
Trying to load any presets for advancements, loot tables, or recipes for 1.21 comes up with an error.

## Crash report
 * Page url: `https://misode.github.io/loot-table/?version=1.21`
 * Generator ID: `loot_table`
 * Current version: `1.21`
 * Latest version: `24w20a`

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:chest",
  "random_sequence": "minecraft:pots/trial_chambers/corridor"
}
</pre>
</details>

**Comment by misode** [comment]
This should be fixed in d849fca07e92a36018e83ca0d2491d60401232f1
