### ISSUE TITLE
Option for export larger noise image without scaling

### ISSUE THREAD

**Issue by SettingDust** [misode/misode.github.io#533]
Context: https://github.com/misode/misode.github.io/discussions/532

The canvas can save in context menu that is disabled in generator. 
The scaled noise pixels are merged. It's useful to find out the distribution of the noise with histogram of grayscale.

**Comment by misode** [comment]
This is out of scope for the website. If you want the raw data of the noise visualizer you can use the [deepslate](https://github.com/misode/deepslate) library directly
