### ISSUE TITLE
[Enhancement] Option to sort keys in JSON alphabetically

### ISSUE THREAD

**Issue by Apollounknowndev** [misode/misode.github.io#537]
Title mostly says it all. Vanilla sorts keys in the default json files alphabetically (excluding the `type` key which always comes first). It would be nice to have this sorting as an option, especially for when building off of vanilla files.

**Comment by misode** [comment]
Would you want this as an option for the JSON output or for the editor view?

**Comment by Apollounknowndev** [comment]
> Would you want this as an option for the JSON output or for the editor view?

Both would be awesome but since it'd be useful mainly for consistency with files that haven't gone through the generator, just having it as the output would be enough.
