### ISSUE TITLE
Undeletable file

### ISSUE THREAD

**Issue by miniking1000** [misode/misode.github.io#540]
If you save file with bad symbols, you wont be able to delete/rename it.

How to reproduce:
1)create a file(I was doing advancements) and save it as **name/**.json
2)done. now file is just there. and you can't delete it, or rename it.

**Comment by misode** [comment]
I cannot reproduce this. What exactly do you mean with "bad symbols"? Could you share the exact file name that is causing issues for you @miniking1000?

**Comment by miniking1000** [comment]
This all because of this symbol ->  \  <- (U+005C)

you can do it with any name if it ends with it, for example 'name\' or 'haha\'

**Comment by misode** [comment]
Thank you, I can confirm now!

**Comment by misode** [comment]
I decided to fix this by validating the file names when you save or rename a file. For now it is still impossible to delete or open files with invalid characters already in them (due to importing a project zip for example), but I may revisit that in the future
