### ISSUE TITLE
SyntaxError: Error importing: Unexpected token :

### ISSUE THREAD

**Issue by AngelOfDeath0434** [misode/misode.github.io#541]
## Crash report
 * Page url: `https://misode.github.io/assets/model/?version=1.20`
 * Generator ID: `model`
 * Current version: `1.20`
 * Latest version: `1.21`

### Stack trace
```
SyntaxError: Error importing: Unexpected token :
    at Ei (../../node_modules/comment-json/src/parse.js:87:16)
    at unexpected (../../node_modules/comment-json/src/parse.js:422:4)
    at parse (src/app/services/Source.ts:24:23)
    at async (src/app/services/Source.ts:43:8)
    at async (src/app/components/generator/SourcePanel.tsx:71:17)
```

### Generator JSON
<details>
<pre>
{
  "parent": "minecraft:item/generated",
  "textures": {
    "layer0": "minecraft:item/netherite_leggings"
  },
  "overrides": [
    {
      "predicate": {
        "trim_type": 0.1
      },
      "model": "minecraft:item/netherite_leggings_quartz_trim"
    },
    {
      "predicate": {
        "trim_type": 0.2
      },
      "model": "minecraft:item/netherite_leggings_iron_trim"
    },
    {
      "predicate": {
        "trim_type": 0.3
      },
      "model": "minecraft:item/netherite_leggings_netherite_darker_trim"
    },
    {
      "predicate": {
        "trim_type": 0.4
      },
      "model": "minecraft:item/netherite_leggings_redstone_trim"
    },
    {
      "predicate": {
        "trim_type": 0.5
      },
      "model": "minecraft:item/netherite_leggings_copper_trim"
    },
    {
      "predicate": {
        "trim_type": 0.6
      },
      "model": "minecraft:item/netherite_leggings_gold_trim"
    },
    {
      "predicate": {
        "trim_type": 0.7
      },
      "model": "minecraft:item/netherite_leggings_emerald_trim"
    },
    {
      "predicate": {
        "trim_type": 0.8
      },
      "model": "minecraft:item/netherite_leggings_diamond_trim"
    },
    {
      "predicate": {
        "trim_type": 0.9
      },
      "model": "minecraft:item/netherite_leggings_lapis_trim"
    },
    {
      "predicate": {
        "trim_type": 1
      },
      "model": "minecraft:item/netherite_leggings_amethyst_trim"
    },
    {
      "predicate": {
        "custom_model_data": 2
      },
      "model": "minecraft:item/demon_leggings"
    },
    {
      "predicate": {
        "custom_model_data": 6
      },
      "model": "minecraft:item/slime_leggings"
    },
    {
      "predicate": {
        "custom_model_data": 15
      },
      "model": "minecraft:item/warden_leggings"
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment]
You likely have a JSON error in the contents that you pasted.
