### ISSUE TITLE
Stringified JSON text in components is not validated

### ISSUE THREAD

**Issue by xa31er** [misode/misode.github.io#549]
When generating a new recipe like this:
`{
  "type": "minecraft:crafting_shaped",
  "category": "equipment",
  "group": "wands",
  "pattern": [
    "  X",
    " # ",
    "#  "
  ],
  "key": {
    "X": {
      "item": "minecraft:diamond"
    },
    "#": {
      "item": "minecraft:stick"
    }
  },
  "result": {
    "id": "minecraft:carrot_on_a_stick",
    "count": 1,
    "components": {
      "minecraft:custom_model_data": 1,
      "minecraft:custom_name": "Diamond Wand"
    }
  }
}
`
The output the generator gives (that text ^^^) doesn't work ingame.

The error is malformed JSON @ the "minecraft:custom_name":"Diamond Wand" line.

Thank you for the help.

**Comment by misode** [comment]
You need to quote the JSON text manually in the "custom_name" field

**Comment by xa31er** [comment]
Thank you!
(Sorry I couldn't respond earlier)

**Comment by misode** [comment]
I'll actually keep this issue open, because I want to add validation to these fields
