### ISSUE TITLE
Component generators erroneously allow for un-namespaced components

### ISSUE THREAD

**Issue by DorkOrc** [misode/misode.github.io#551]
Component generators allow for un-namespaces components like so:
![image](https://github.com/misode/misode.github.io/assets/16517352/dc75bd77-ad52-45a6-b14f-1418c8087bf2)
![image](https://github.com/misode/misode.github.io/assets/16517352/016956c5-cf52-4afc-804a-ee424f89ef12)

It gives an error but still recognises the component, and it writes it in the output without a namespace (which can lead to inconsistency).

**Comment by misode** [comment]
It allows you to type any value you want, but given that it shows an error after you do that, I'm going to say this is "won't fix"
