### ISSUE TITLE
Expected an array after "minecraft:crossbow_charge_time"

### ISSUE THREAD

**Issue by 4strodec** [misode/misode.github.io#554]
In the Enchantment Generator the effect "minecraft:crossbow_charge_time" needs an array, tho it only needs curly brackets {}.

**Comment by misode** [comment]
I don't think that's the case. After looking at the decompiled code, and reading the official patch notes:
> minecraft:crossbow_charge_time: Effects for the charging time of a Crossbow
Format: A single Value Effect on the charge time of the Crossbow in seconds - unconditional

It seems like it expects a single value effect
