### ISSUE TITLE
Cannot find generator "/%C3%A3%C2%80%C2%80%C3%A4%C2%BD%C2%9C%C3%A8%C2%80%C2%85"

### ISSUE THREAD

**Issue by pomionot** [misode/misode.github.io#556]
## Crash report
 * Page url: `https://misode.github.io/%C3%A3%C2%80%C2%80%C3%A4%C2%BD%C2%9C%C3%A8%C2%80%C2%85`
 * Current version: `1.21`
 * Latest version: `1.21`

**Comment by misode** [comment]
I'm not sure what you expected with this URL. From where did you get this link?
