### ISSUE TITLE
The translation website is no longer able to register

### ISSUE THREAD

**Issue by fuuuuuuuuuuuuuuck** [misode/misode.github.io#559]
It seems that the translation website is unable to register a new account, which makes it impossible for me to translate.
If I don't log in, the translation website won't allow me to view any content, but it won't send me a confirmation email.
I tried to translate the content in src/locals, but it seems that it does not cover all strings.

**!This issue is unique!**
I have searched the issue tracker and did not find an issue describing my issue.

**Comment by fuuuuuuuuuuuuuuck** [comment]
I translated some new strings into zh_cn (not all): 
[zh_cn.json](https://github.com/user-attachments/files/16117011/zh_cn.json)

**Comment by misode** [comment]
Thank you for the translations, I've pushed them to the site! Unfortunately I don't maintain the translation site, so I can't troubleshoot any registration issues that appear to be happening, that would be a task for @SPGoding, but I know she's very busy.

**Comment by SPGoding** [comment]
I'm working on a solution for localization that doesn't involve me doing system admin work but there's no ETA on when that'll be available yet.
