### ISSUE TITLE
Dimension Generator Overworld Present shows doubles/triples

### ISSUE THREAD

**Issue by ShaneBeee** [misode/misode.github.io#563]
When using the overworld dimension preset for 1.21, there's doubles/triples/more of the biomes:

<img width="536" alt="Screenshot 2024-07-10 at 9 03 51 PM" src="https://github.com/misode/misode.github.io/assets/20008482/cb8e4adc-239e-49fa-b3ed-f50fee9fad0b">
<img width="536" alt="Screenshot 2024-07-10 at 9 03 59 PM" src="https://github.com/misode/misode.github.io/assets/20008482/86e3bf71-30fe-4356-81a8-f48f7cb13b9b">

**Comment by misode** [comment]
Intended. This is how the vanilla biome layout is.

**Comment by ShaneBeee** [comment]
> Intended. This is how the vanilla biome layout is.

gotcha. Thank you for letting me know 👍🏻
