### ISSUE TITLE
Advancement generator formats custom names with only double quotes, where single and double seem to be required

### ISSUE THREAD

**Issue by BlueGuineaPig78** [misode/misode.github.io#576]
Using the advancement generator to detect items with minecraft:custom_name generates an item component section with double quotes surrounding the name:

`"item": {
          "items": "minecraft:saddle",
          "components": {
            "minecraft:custom_name": "Reynard"
          }
        }`

This gets flagged by spyglass in VSCode as expecting ", even though they are clearly there. Adding single quotes "'Reynard'" allowed the advancement to load and work in game. (Spyglass still complains about this formatting.)

**Comment by misode** [comment]
The technically correct syntax is `"\"Reynard\""`.
- As for why this is not validated on the website: #549
- As for why this still warns in Spyglass: https://github.com/SpyglassMC/Spyglass/issues/1309
