### ISSUE TITLE
TypeError: Something went wrong rendering the generator: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by Rbyteria** [misode/misode.github.io#600]
## Crash report
 * Page url: `https://misode.github.io/loot-table/`
 * Generator ID: `loot_table`
 * Current version: `1.21`
 * Latest version: `24w37a`

### Stack trace
```
TypeError: Something went wrong rendering the generator: Cannot read properties of undefined (reading 'indexOf')
    at Ci.parse (../../node_modules/deepslate/lib/core/Identifier.js:32:23)
    at parse (src/app/components/previews/LootTable.ts:392:17)
    at item (src/app/components/previews/LootTable.ts:276:44)
    at compositeFunction (src/app/components/previews/LootTable.ts:264:2)
    at entryConsumer (src/app/components/previews/LootTable.ts:235:3)
    at entries (src/app/components/previews/LootTable.ts:166:15)
    at pool (src/app/components/previews/LootTable.ts:127:15)
    at generateTable (src/app/components/previews/LootTable.ts:48:1)
    at generateLootTable (src/app/components/previews/LootTablePreview.tsx:54:9)
    at n (../../node_modules/preact/hooks/dist/hooks.module.js:1:902)
```

### Generator JSON
<details>
<pre>
{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:alternatives",
          "children": [
            {
              "type": "minecraft:dynamic",
              "name": "minecraft:contents",
              "conditions": [
                {
                  "condition": "minecraft:match_tool",
                  "predicate": {
                    "items": "minecraft:air",
                    "components": {
                      "minecraft:custom_data": "drop_contents:1b"
                    }
                  }
                }
              ]
            },
            {
              "type": "minecraft:item",
              "name": "minecraft:yellow_shulker_box",
              "functions": [
                {
                  "function": "minecraft:copy_name",
                  "source": "block_entity"
                },
                {
                  "function": "minecraft:copy_custom_data",
                  "source": "block_entity",
                  "ops": [
                    {
                      "source": "Lock",
                      "target": "BlockEntityTag.Lock",
                      "op": "replace"
                    },
                    {
                      "source": "LootTable",
                      "target": "BlockEntityTag.LootTable",
                      "op": "replace"
                    },
                    {
                      "source": "LootTableSeed",
                      "target": "BlockEntityTag.LootTableSeed",
                      "op": "replace"
                    }
                  ]
                },
                {
                  "function": "minecraft:set_contents",
                  "entries": [],
                  "count": 1
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
</pre>
</details>

**Comment by misode** [comment]
Same issue as #604, now fixed!
