### ISSUE TITLE
Custom biome generator sound id format has changed

### ISSUE THREAD

**Issue by winderine** [misode/misode.github.io#609]
Output of generator is 
```
    "mood_sound": {
      "sound": "namespace:sound.event",
      "tick_delay": 0,
      "block_search_extent": 0,
      "offset": 0
    }
```

Which will not load in minecraft 1.21

Needs to be 
```
    "mood_sound": {
      "sound": {
          "sound_id": "namespace:sound.event"
           },
      "tick_delay": 0,
      "block_search_extent": 0,
      "offset": 0
    }
```

Apparently this was added as experimental in 1.19.3 and never removed

https://gist.github.com/boq/08ec7cd9691967d907286b5aa5d6c230

**Comment by misode** [comment]
This is already correctly implemented. You just need to switch to object mode yourself whenevr you're working with custom sounds.
![image](https://github.com/user-attachments/assets/09a7f086-7c12-4f7a-aeda-b73da78ba02a)

This could maybe be improved by providing a list of vanilla sound events though.

**Comment by winderine** [comment]
Sorry, I don't understand. How do you mean switch to object mode? I posted
this because the generator doesn't work for adding sounds to biomes at all.

**Comment by misode** [comment]
Check my screenshot. Where you're inputting the sound, you need to switch the "string" mode to "object"

**Comment by winderine** [comment]
Okay, I didn't see that dropdown when I was trying to get the default to
work. What is string used for then? As I said, I couldn't get the default
"string" option to work at all, whether with vanilla sound events, vanilla
sound file locations, or sound events added via resource pack - datapacks
using this format did not load at all.
