### ISSUE TITLE
Question for Misode

### ISSUE THREAD

**Issue by RSNFreud** [misode/misode.github.io#612]
Hey @misode,

Wanted to check if I'm allowed to clone this repositry and privately host a custom version for a modpack I'm creating. We have a number of new datapack functions we've added and would make our life much easier to be able to use a tool such as what you made

**Comment by misode** [comment]
Yeah that is allowed, as long as you follow the license (MIT). When deploying your own version of the website, you should think of: (1) disabling google analytics, and (2) disabling the ads. See lithostiched ([source](https://github.com/apollounknowndev/misode.github.io/tree/lithostitched)) ([deployed site](https://lithostitched.vercel.app/)) as a reference.

**Comment by RSNFreud** [comment]
> Yeah that is allowed, as long as you follow the license (MIT). When deploying your own version of the website, you should think of: (1) disabling google analytics, and (2) disabling the ads. See lithostiched ([source](https://github.com/apollounknowndev/misode.github.io/tree/lithostitched)) ([deployed site](https://lithostitched.vercel.app/)) as a reference. Feel free to reach out to me on discord if you need help.

Thanks! Is there any documentation on how the schemas and such work?

**Comment by RSNFreud** [comment]
Also whats your discord username?

**Comment by misode** [comment]
There isn't any documentation on this sadly. But to warn you, I am working on rewriting this part so that in the future all schemas will be written in the mcdoc format. This is a much easier way to define generators. I hope to finish this in a couple if months, so maybe you can afford to wait until then.

**Comment by RSNFreud** [comment]
I've already wrote it up haha but can always rewrite later

**Comment by misode** [comment]
> Also whats your discord username?

`@misode`

If you have trouble finding me, I'm also on the MinecraftCommands discord.
