### ISSUE TITLE
Request: 24w14potato

### ISSUE THREAD

**Issue by Tamamo-no-Bae** [misode/misode.github.io#622]
Any chance you could add support for this snapshot version? I am working on a datapack for it to depotatofy the snapshot and turn the potato into the Aether.

However I need to be able to edit the biome color, dimension color, item attributes, villager trades, etc.
And I cant find out how to get that stuff out of the version.

(20w14infinite would be nice too tbh)

**Comment by misode** [comment]
I'm not really planning to support these versions. You could probably fork the repo and make some modifications, but it's not easy. Both mcmeta and the schemas don't exist for those versions.
