### ISSUE TITLE
update Lychee to support newer versions

### ISSUE THREAD

**Issue by hedkne43rei0pow** [misode/misode.github.io#624]

**Comment by misode** [comment]
I'm not sure what you mean with "Lychee support". I don't know what Lychee is.

**Comment by hedkne43rei0pow** [comment]
the lychee data pack thing
it doesn't support newer versions of the mod
(or am I asking in the wrong place/person?)

**Comment by misode** [comment]
You're probably in the wrong place. If the Lychee mod has a fork of my website, you should tell them to modify the link to the github repo. This repository has never had generators for the Lychee mod.
