### ISSUE TITLE
Error: Cannot get version "1.21": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.09bb7867.js

### ISSUE THREAD

**Issue by Kyberilium08** [misode/misode.github.io#634]
## Crash report
 * Page url: `https://misode.github.io/jukebox-song/`
 * Generator ID: `jukebox_song`
 * Current version: `1.21`
 * Latest version: `1.21.2-pre3`

### Stack trace
```
Error: Cannot get version "1.21": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.09bb7867.js
Error: Cannot get version "1.21": Failed to fetch dynamically imported module: https://misode.github.io/assets/index.09bb7867.js
    at (https://misode.github.io/assets/index.a5dc4821.js:135:155239)
```

### Generator JSON
<details>
<pre>
{
  "sound_event": "music.overworld.deep_dark",
  "description": {
    "text": "Lena Raine - Ancestry / Deeper",
    "hoverEvent": {
      "action": "show_text",
      "contents": {
        "text": "Lena Raine - Ancestry / Deeper"
      }
    }
  },
  "length_in_seconds": 343,
  "comparator_output": 0
}
</pre>
</details>

**Comment by misode** [comment]
Did you have the page open for a while before trying to switch versions? This error is usually a sign that a new build was triggered but right now that was two weeks ago...
