### ISSUE TITLE
inverted predicate website crash

### ISSUE THREAD

**Issue by Bananaguns2** [misode/misode.github.io#642]
I'm using the latest web build of this amazing tool & whenever I go to use the inverted predicate(condition) it just crashes & it says in the banner if you think this is a bug report it to the author. Is the inverted predicate missing for minecraft 1.20.1? I never used this to generate new minecraft loot tables yet because the moding scene is still behind the development of the game. I'll sometimes play vanilla if they finish a update cycle like rn they're still running update cycles for 1.21 a example of this is minecraft 1.19 wasn't fully out until release 1.19.2 & they were pushing snapshots for 1.20 so technically 1.21 is still not fully out in my opinion. Is what I'm experiencing a bug with the latest build of the tool I love so dang much? If your primary language is not English so so sorry for the huge rant either way.

**Comment by misode** [comment]
Hey! I'm havving trouble reproducing the issue. When the red banner shows, could you click the button to report it? It will provide with some extra details containing the error information and the current JSON that you had loaded.

**Comment by Bananaguns2** [comment]
URL is too long according to Google

**Comment by Bananaguns2** [comment]
at condition (src/app/components/previews/LootTable1204.ts:406:24)
    at testCondition (src/app/components/previews/LootTable1204.ts:443:10)
    at ctx (src/app/components/previews/LootTable1204.ts:407:60)
    at testCondition (src/app/components/previews/LootTable1204.ts:394:8)
    at ctx (src/app/components/previews/LootTable1204.ts:220:50)
    at canEntryRun (src/app/components/previews/LootTable1204.ts:180:6)
    at expandEntry (src/app/components/previews/LootTable1204.ts:192:8)
    at entry (src/app/components/previews/LootTable1204.ts:150:16)
    at pool (src/app/components/previews/LootTable1204.ts:125:15)
    at generateTable (src/app/components/previews/LootTable1204.ts:43:1)

**Comment by Bananaguns2** [comment]
Here's the code before it crashes it I tried adding inverted to the 1st lapis lazuli in the 1st loot `table``

{
  "type": "minecraft:block",
  "pools": [
    {
      "rolls": 1,
      "entries": [
        {
          "type": "minecraft:alternatives",
          "children": [
            {
              "type": "minecraft:item",
              "name": "minecraft:deepslate_lapis_ore",
              "conditions": [
                {
                  "condition": "minecraft:match_tool",
                  "predicate": {
                    "enchantments": [
                      {
                        "enchantment": "minecraft:silk_touch"
                      }
                    ]
                  }
                }
              ]
            },
            {
              "type": "minecraft:item",
              "name": "minecraft:lapis_lazuli",
              "functions": [
                {
                  "function": "minecraft:set_count",
                  "count": 9
                }
              ],
              "conditions": []
            }
          ],
          "conditions": []
        }
      ]
    },
    {
      "rolls": 9,
      "entries": [
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 2
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 1
                  }
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 3
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 2
                  }
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 4
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 3
                  }
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 5
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 4
                  }
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 6
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 5
                  }
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 7
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 6
                  }
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 8
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 7
                  }
                ]
              }
            }
          ]
        },
        {
          "type": "minecraft:item",
          "name": "minecraft:lapis_lazuli",
          "functions": [
            {
              "function": "minecraft:set_count",
              "count": 9
            }
          ],
          "conditions": [
            {
              "condition": "minecraft:match_tool",
              "predicate": {
                "enchantments": [
                  {
                    "enchantment": "minecraft:fortune",
                    "levels": 8
                  }
                ]
              }
            }
          ]
        }
      ]
    }
  ]
}
