### ISSUE TITLE
Pack.mcmeta generator generating a "pack_mcmeta" folder instead.

### ISSUE THREAD

**Issue by EightySiix** [misode/misode.github.io#644]
![Screenshot 2024-11-28 163711](https://github.com/user-attachments/assets/024e5b5a-29dc-4c51-bf7d-c476f4fbdfe3)
damn.

**Comment by Doc94** [comment]
Same issue here.. i cannot move the file or try any.. the save file just create the directory or in a random case (only get this one time) the file was saved in data and not in "root"

**Comment by misode** [comment]
Thanks for the report! Should be fixed now.
