### ISSUE TITLE
chest special model type doesnt recognize the "texture" key

### ISSUE THREAD

**Issue by DMgaming100** [misode/misode.github.io#647]
you can reproduce the issue by simply loading the chest preset and see you get this alert
![image](https://github.com/user-attachments/assets/ee4fb5d9-85e0-4b9e-9aa5-87071b117462)

**Comment by misode** [comment]
Fixed in https://github.com/SpyglassMC/vanilla-mcdoc/commit/a8962a1443ef253b92cc39dbbf8027aeaf5e0d30
