### ISSUE TITLE
Noise Settings unable to be viewed outside of preview. 

### ISSUE THREAD

**Issue by comacrow** [misode/misode.github.io#650]
When attempting to view a file in the noise_settings folder the majority of the file is unable to be viewed or edited outside of the preview window. 

To replicate:
Add existing datapack with noise_settings folder to new project or use noise setting preset (overworld).
Scroll down to "surface rule" and click to expand
See vast majority of file is hidden/inaccessible outside of preview

Issue started on 11/27th/2024

**Comment by misode** [comment]
I need some more info to reproduce. Could you share a file that causes the issues for you? Could you maybe share a screenshot or recording of the bug happening?

**Comment by comacrow** [comment]
Here is a video showing the issue using a fresh download of the Cliff Under A Tree v1.8 worldgen datapack and the default overworld preset. Sorry for the weird colors, that happened while trimming/cropping the video. 

https://github.com/user-attachments/assets/1b98f3ef-cc30-4d94-aba8-9080cba301a8

**Comment by comacrow** [comment]
I am very sorry about closing and reopening the issue. I'm not super familiar with Github so I accidently clicked close when trying to upload my reply.

Here is a video showing the issue with a fresh download of the Cliff Under a Tree v1.8 wordgen datapack and the default overworld preset. Sorry for the weird colors, that happened while trimming/compressing the video. 

Uploading Desktop2024.12.03-18.34.18.02-Trim-ezgif.com-crop-video (1).mp4…

**Comment by misode** [comment]
Uploading the video didn't seem to have worked. Could you please try again? @comacrow

**Comment by comacrow** [comment]
Very odd, this version seems to be working: 
https://github.com/user-attachments/assets/6c1d6ab0-1240-403c-8dac-eb2dd2cda784

**Comment by misode** [comment]
Oh you mean that the surface rules are collapsed by default. This was done for performance reasons. You can expand them all individually. Are you looking for an option to expand them all at the same time?

**Comment by comacrow** [comment]
Oh! I didn't see how to properly expand them, sorry. If it doesn't exist already an option to expand them all would definitely be helpful since it's very tedious to open them all individually but it's understandable if thats not possible for whatever reason like performance.
