### ISSUE TITLE
Is it possible to provide the ability to use the older version.

### ISSUE THREAD

**Issue by wonderfulaichen** [misode/misode.github.io#657]
Whether it is possible to provide the ability to switch to the previous version after updating the website, or whether it is a local program. 

You can't get halfway through the project, you have to adapt to new features, and you can't use the previous code due to new bugs. This causes the packet item to slow down or stop. 

"Now I can't do it because of a bug in the dimension."

**Comment by misode** [comment]
You could build the website locally or fork if from an older version, but I'm not providing support for it. Is the issue that you're encountering caused by #651?
