### ISSUE TITLE
Support generating resources in the site/app from custom mcdoc

### ISSUE THREAD

**Issue by MulverineX** [misode/misode.github.io#658]
Two methods should be provided; uploading an mcdoc file/zip of files or deep linking to a generated symbol table (`https://misode.github.io/custom-mcdoc?symbols_url=https%3A%2F%2Fgithub.com%2FSpyglassMC%2Fvanilla-mcdoc%2Fblob%2Fgenerated%2Fsymbols.json%3Fraw%3Dtrue`)

**Comment by misode** [comment]
I'm not sure I want to do it like that tbh. There's already a fairly easy way to add custom generators, under the "Modded Generators"

**Comment by MulverineX** [comment]
Those aren't mcdoc though, and imo aren't anywhere near as easy to make.

**Comment by misode** [comment]
They are since the mcdoc rewrite https://github.com/misode/misode.github.io/tree/master/public/mcdoc

**Comment by MulverineX** [comment]
oh lmao great, nvm
