### ISSUE TITLE
Add Sky Aesthetics for modded generators

### ISSUE THREAD

**Issue by TathanDev** [misode/misode.github.io#664]
Hey !

I'm the dev of a mod named Sky Aesthetics that allow the player to modify the world sky with a resourcepack.
I was wondering if it was possible for me to create a pull request that add a generator Sky Aesthetics.

Informations about Sky Aesthetics
- [modrinth](https://modrinth.com/mod/sky-aesthetics)
- [github ](https://github.com/TathanDev/SkyAesthetics)
- [wiki](https://github.com/TathanDev/SkyAesthetics/wiki)

Thanks for the answer !

**Comment by misode** [comment]
Yeah that would definitely be possible! After forking and setting, you'll need to make the following changes:
1. Add a `.mcdoc` file in `public/mcdoc/`. This is the bulk of the work, defining the schemas. For some examples on how they work, you can look at the other files in that folder, or [vanilla-mcdoc](https://github.com/SpyglassMC/vanilla-mcdoc)
2. Create a generator entry in `src/config.json` (below line 714)
3. Add localization keys for the generator name in `src/locales/en.json`.

That should be mostly it, feel free to let me know if you need further help!
