### ISSUE TITLE
Inverting requirement of AND connection causes redundancy

### ISSUE THREAD

**Issue by HalbFettKaese** [misode/misode.github.io#72]
Currently, an AND connection between different conditions is generated by inverting both the result and the inputs of an OR connection.

However, when one of the requirements is the `minecraft:inverted` condition, that causes the generated text to have and inverted condition within an inverted condition, which is completely redundant.

**Comment by misode** [comment]
Yep I also noticed this. A double inverted condition should get collapsed.
