### ISSUE TITLE
tool_enchantment condition missing

### ISSUE THREAD

**Issue by HalbFettKaese** [misode/misode.github.io#77]
Loot tables do not give the option of choosing the `minecraft:tool_enchantment` condition on block loot tables.

This is not an important issue because `minecraft:match_tool` is supported, but it prevents some loot tables from loading properly and does remove the more direct option and introduces some potential redundancy.

**Comment by misode** [comment]
Weird that I forgot about this condition. I see it was added in [18w43a](https://github.com/misode/MinecraftArticles/search?q=tool_enchantment&unscoped_q=tool_enchantment). Shouldn't be difficult to add this.

**Comment by misode** [comment]
From my testing it appears that `tool_enchantment` never made it into the full release. The log gives an  error `Unknown condition 'minecraft:tool_enchantment'`.
