### ISSUE TITLE
table_bonus condition malformed

### ISSUE THREAD

**Issue by HalbFettKaese** [misode/misode.github.io#84]
The `table_bonus` condition for predicates and loot tables fills in strings instead of numbers in most cases, and the UI is unintuitive:
* Entering any normally valid integer or float results in the value being converted to string. This does not happen when a number with an invalid amount is entered, which corrects it to be either `0` or `1` as integers instead of strings.
* Unlike other list-type tags, it does not feature a separate button to add entries but instead requires the user to add commas between the values.

**Comment by misode** [comment]
I have fixed the chances converting to strings and added some an info tooltip explaining the format. No further chances are planned to improve this further at the moment.
