### ISSUE TITLE
Advancements are missing support for the "requirements" list

### ISSUE THREAD

**Issue by HalbFettKaese** [misode/misode.github.io#88]
When importing the following advancement into the advancement generator, the `requirements` tag gets removed despite being used by the game and being needed to make OR connections:
```
{
  "criteria": {
    "c2": {
      "trigger": "minecraft:impossible"
    },
    "c1": {
      "trigger": "minecraft:impossible"
    }
  },
  "requirements": [["c1", "c2"]]
}
```

**Comment by misode** [comment]
I remember I encountered some technical difficulties. Definitely a bug but not sure when this will be implemented

**Comment by misode** [comment]
This has been fixed in the dev version: https://misode.github.io/dev/advancement/
