### ISSUE TITLE
Unintuitive UX with vanilla dimensions

### ISSUE THREAD

**Issue by kevATin** [misode/misode.github.io#89]
I think it would be easier to make little changes to vanilla dimensions if, when you uncollapse the "Generator Settings" and "Dimension Options", they don't instantly revert to the default settings for "Overworld" and "Default" respectively.
Instead the values that are internally used by those presets should carry over into the custom settings menu, so you can make little changes to the Nether without having to first copy all the Nether values and then paste them over the Overworld values that got defaulted in.

I don't know how the code works on Minecraft's end, if those presets are hardcoded and do more than just change some values then this might not be feasible, but I don't think that's the case.

**Comment by misode** [comment]
The way they currently work is a bit of a hack so I'm not sure how feasible it would be. I understand that the current behavior is unintuitive so I will see what's possible.

**Comment by misode** [comment]
This suggestion made it into the new version of the generator, which you can find here: https://misode.github.io/dev/dimension/
