### ISSUE TITLE
Missing loot table function minecraft:set_loot_table

### ISSUE THREAD

**Issue by ManosSef** [misode/misode.github.io#93]
I know why you forgot this one. The wiki said nothing about it and nobody had heard about it. But today I ran the data generator of 1.16.1 and found that it exists. Its parameters are "name" for the loot table name, and "seed" for the loot table seed. I added it to the wiki. I don't blame you for not adding it, nobody knew about it.

**Comment by misode** [comment]
I remember seeing it in the original changelog a few times but forgot about it. Thanks for making an issue.
