### ISSUE TITLE
World gen generator needs to be changed

### ISSUE THREAD

**Issue by Nathan22211** [misode/misode.github.io#96]
1. Dimensions are now defined in datapacks, each as separate files
2. The seed field is now optional
3. Custom biomes are now possible. 20w28a+
4. Custom structures are now possible without something like Orbis. 20w28a+

bit more reference if you look into the game's data folder or Slicedlime's series he's doing on this https://www.youtube.com/watch?v=hf4jinDtR14&t=629s

**Comment by ManosSef** [comment]
Dimensions are still also defined using the import button as well as with data packs

**Comment by misode** [comment]
This will not be added to the current generator. A new version is being worked on: https://misode.github.io/dev/worldgen/
